### PR TITLE
Change n_shifts to exclude_sweep_ms

### PR DESCRIPTION
**Pull request by yger**
I think that for peak detection, n_shifts is a bad and non explicit name. Why not time_radius_ms, to be similar to local_radius_um ? Best if the parameter is given in ms and not in time steps

### CODE REVIEW

**Comment by alejoe91** [comment]
I vote for `exclude_time_ms`

**Comment by yger** [comment]
Ok. But then, should I also rename local_radius_um to exclude_radius_um ?

**Comment by samuelgarcia** [comment]
I vote for `exclude_sweep_ms` and I also vote for keeping `n_shifts` internally and also as an input that would be mutually exclusive of this params.

**Comment by yger** [comment]
Time to agree guys. I don't like having two mutually exclusive arguments.. and the names, I don't care, juste need to be consistent with the spatial radius

**Comment by samuelgarcia** [comment]
This is for not breaking backwarg compatibility. Many other script depend on this.
We have to be a bit smart with existing pipeline.

**Comment by yger** [comment]
Ok deal. I'll keep n_shifts then. And of you want exlude_sweep_ms why not, as said, I'm open minded. I just feel that there is a slight lack of consistency because spatio-temporel exclusions are similar, but let's go, I'll push that this morning

**Review by samuelgarcia — APPROVED** [review]

**Pull request merged**
