### PR TITLE
Remove __del__ from nwbextractor

### PR DESCRIPTION
**Pull request by alejoe91**
Fix https://github.com/SpikeInterface/spikeinterface/issues/457

Not sure if we should rely on Python to handle file closing or to propagate the file opening to the recording segment.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
I am pretty sure it will fix.
@khl02007  : can you test this ?

**Comment by alejoe91** [comment]
@samuelgarcia it fixes it on my side!

**Comment by samuelgarcia** [comment]
Can I merge this or is it still a draft ?

**Comment by alejoe91** [comment]
> Can I merge this or is it still a draft ?

Let's merge for now ;)

**Review by samuelgarcia — APPROVED** [review]

**Comment by khl02007** [comment]
@alejoe91 @samuelgarcia Yes this fixes the issue - thanks! Just curious: so does the nwb file never get closed now even after all references are gone?

**Pull request merged**
