### PR TITLE
Added from_peaks NumpySorting

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
This is mostly an internal need because the label is taken by the channel.
This should be clearly documented.

**Comment by alejoe91** [comment]
> This is mostly an internal need because the label is taken by the channel. This should be clearly documented.

You mean in the `detect_peaks()` function?

**Comment by samuelgarcia** [comment]
peak to sorting is a non sens. But we internaly use it because we make a fake sorting where peaks are labeled by channel detection. And so we use it to extract waveform on it by channel.
It would be more logical to have a set of function for waveform extraction peaks vector.
I don't think this is very relevant for the end user.

**Comment by alejoe91** [comment]
> peak to sorting is a non sens. But we internaly use it because we make a fake sorting where peaks are labeled by channel detection. And so we use it to extract waveform on it by channel. It would be more logical to have a set of function for waveform extraction peaks vector. I don't think this is very relevant for the end user.

but for us it is

**Pull request merged**
