### PR TITLE
Circus2 pipeline

### PR DESCRIPTION
**Pull request by yger**
Fixing some small bugs in the OMP peeler, and enhancing spykingcircus2. Figures for Sam will follow soon :-)

### CODE REVIEW

**Comment by yger** [comment]
@merging that ? Bugs should be fixed, peeler is fine, I guess this will be rather stable from now on. I'll benchmarks that for next meeting, presenting results

**Comment by alejoe91** [comment]
@yger happy with this?

**Comment by yger** [comment]
Yes and no. Yes, because results are good, but no because ideally, I should make my peeler robust to chunk sizes (results are the same, but the speed is not). Maybe we can leave it aside for now, don't know. This is just optimization, but the circus-omp peeler will not work if chunk of more than hundreds of ms are given, currently

**Comment by alejoe91** [comment]
@yger 2 things:

1. can you add SpykingCircus2 in the docs (installed sorters)?
2. When `n_jobs=-1`, can you set `n_jobs=os.cpu_count()`? Otherwise it fails on Windows

**Comment by alejoe91** [comment]
@yger just pushed some small changes to the docs. 

Ready to merge on my side. @samuelgarcia ?

**Review by alejoe91 — APPROVED** [review]

**Pull request merged**
