### PR TITLE
Correct GH handle for sortingview curation tests

### LINKED ISSUE #1530: Full tests failing on main. Curation tests responsably
This has been failing for a couple of days now:
https://github.com/SpikeInterface/spikeinterface/actions/runs/4678057825/jobs/8286320991

I think this cuaration tests has failed before. It seems that it can't connect or download the correct file.

```
FAILED src/spikeinterface/curation/tests/test_sortingview_curation.py::test_gh_curation - Exception: Could not retrieve curation from SortingView uri: gh://SpikeInterface/spikeinterface/master/spikeinterface/curation/tests/sv-sorting-curation.json
= 1 failed, 465 passed, 24 skipped, 41 deselected, 92 warnings in 4018.36s (1:06:58) =
```

@alejoe91 I think that you modified this recently, I don't know the curation module well, any idea of what this could be?

### PR DESCRIPTION
**Pull request by alejoe91**
Fixes #1530

### CODE REVIEW

**Comment by alejoe91** [comment]
@h-mayorquin not sure why tests are failing!

**Comment by h-mayorquin** [comment]
Ah, this is the other error that is ongoing even before #1516. I will attempt to fix it. Meanwhile, you can re-run the tests any time you see this issue.

**Comment by h-mayorquin** [comment]
This should be fixed once #1532 is merged. #1532 is ready now.

**Review by h-mayorquin — APPROVED** [review]
Ah, glad it was soo easy!

**Comment by alejoe91** [comment]
Not sure why tests are failing though! Seems unrelated?

**Comment by h-mayorquin** [comment]
Damn, I was dumb enough to not change the specific files concerning this activation to use the environment variables for the path. This type of error should be less likely with the changes in #1533.

**Comment by h-mayorquin** [comment]
@alejoe91 https://github.com/SpikeInterface/spikeinterface/pull/1533 is ready and should solve the issue here.

**Pull request merged**
