### PR TITLE
adds mask out artifacts

### PR DESCRIPTION
**Pull request by ferchaure**
Hi guys,

We talk a bit about this on #363. The idea is to divide each recordingsegment in chunks of 2000 frames and calculate the energy of each. After filtering, the chunks with high energy (over a threshold) are usually just noise. This is a simple way to remove artifacts that could complicate spike sorting later.

To get the statistics for the threshold (standard deviation approx using MAD) I uses 10% of randomly selected chunks (probably I should use a higher value). I save in an internal vector if each chunk is already calculated and masked out. 

This is a simplified version of [this code](https://github.com/magland/ml_ephys/blob/master/ml_ephys/preprocessing/p_mask_out_artifacts.py) from magland. Following his code if any channel cross the threshold al the recordings at these frames are mask out (I think is a good behaviour is the threshold is high enough and bad channels are already removed). Nevertheless, to make this a bit more permissive I added an easy way to split the recording by property (I used this method a lot dividing by probe).

Let me know what you think... sorry for the low quality docs, I'm still learning about the style.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Fernando.
I will read this soon in detail.
Did you know that we already have a `get_random_data_chunk()` and et_noise_levels` that can be used to estiomate average/std or median/mad ?
https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/toolkit/utils.py#L5
https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/toolkit/utils.py#L91

**Comment by ferchaure** [comment]
Yes, I checked  both functions, but I couldn't use them because I need  to know which chunks are to save if they are over the threshold or not.

**Comment by alejoe91** [comment]
@ferchaure as discussed together, this needs to be refactored to allow multiprocessing. 
Can I close this for now and we keep the discussion open among us?

**Comment by ferchaure** [comment]
yes it's fine... and I will need more info about what  I can and cannot do on the BasePreprocessorSegment subclasses

**Pull request closed without merging**
