### PR TITLE
Implement merging of AP and LFP channels

### PR DESCRIPTION
**Pull request by DradeAW**

### CODE REVIEW

**Comment by DradeAW** [comment]
The code is really rough and hard to read, I might break it done into smaller functions but I know that @samuelgarcia doesn't like that very much :)

Anyway it's close to being functional.

**Comment by DradeAW** [comment]
@alejoe91 @samuelgarcia I think this is about ready, what do you think about it?

**Comment by alejoe91** [comment]
@DradeAW we moved to the `main` branch, with a `src/spikeinterface` organization.

Could you close this one and open a new one to main? Or we can help to rebase. Let us know!

**Comment by DradeAW** [comment]
@alejoe91 @samuelgarcia Why is the test failing?

Other PR don't seem to be failing ...

**Comment by alejoe91** [comment]
@DradeAW fixed other tests, now yours are failing ;)

**Comment by DradeAW** [comment]
After a lot of hard work, merging of AP and LFP is working!!

The code works, but isn't very pretty as of right now ^^'
@samuelgarcia and @alejoe91 are probably gonna ask me for a lot of changes :stuck_out_tongue:

**Comment by zm711** [comment]
@DradeAW: will you have time to work on this in the future? I haven't followed this story at all, but since the merge conflicts mention sorting analyzer I wonder if this will require a lot of work to fix up? Do you want to leave this open?

**Comment by DradeAW** [comment]
I can find some time to work on it :)

**Pull request closed without merging**
