### PR TITLE
Compiled waveclus

### PR DESCRIPTION
**Pull request by chyumin**
Required changes to run compled waveclus
small improvement on kilosort

### CODE REVIEW

**Comment by chyumin** [comment]
@bendichter I'm not sure what change to submit to waveclus. The matlab files here are specific to spike-interface
I think it's possible to submit the `h5_wc_reader.m` file which waveclus doesn't support for now

**Comment by bendichter** [comment]
@chyumin I'm confused why you need to use h5_wc_reader.m in the first place. Can't you read the results with just Python?

**Comment by bendichter** [comment]
(I am not very familiar with this sorter so this may be incorrect, but quickly looking through the code I wasn't able to find a need for it)

**Comment by chyumin** [comment]
@bendichter I found out that the file is being used [here](https://github.com/csn-le/wave_clus/blob/74e58f5f3db33e1dfb6edd89547d9867ecca96d6/Batch_files/readInData.m#L110). It dinamically uses the filename to check supported file extensions

When I try to run without this file I get this error:
```
Error using readInData (line 128)

File type '.h5' isn't supportedError using readInData 
```

From our side, I also just saw that we're saving as h5 [here](https://github.com/SpikeInterface/spikeinterface/blob/71d5859b0432ea3d02b1b7a5d75e6db7873f6a4e/spikeinterface/sorters/waveclus/waveclus.py#L151). 

A possible option it to change the filetype that we save the recordings from our side to one supported by waveclus by default and get rid of this `h5_wc_reader.m` file. What do you think?

**Comment by chyumin** [comment]
@bendichter 
With [this](https://github.com/csn-le/wave_clus/commit/e51d769a1681823d6b3477d28cc0a5f3491e45f2) commit we now are able to remove the file from spikeinterface. (just removed in my last commit)
Thank you

**Review by alejoe91 — APPROVED** [review]

**Review by alejoe91 — APPROVED** [review]

**Pull request merged**
