### PR TITLE
Updated release notes and pyproject for 0.101.0rc0

### PR DESCRIPTION
**Pull request by alejoe91**
@samuelgarcia 

I would merge this (#2827) first and release 0.100.7 bug fixes.

then this is ready to follow!

### CODE REVIEW

**Comment by zm711** [comment]
Like Heberto I don't fully understand the DEV flag? So in this type of release would the dev be False? Or you don't need to change that?

**Comment by alejoe91** [comment]
@samuelgarcia this is an edge case, what do you think?

**Comment by zm711** [comment]
Also super tiny, but if we decide to do some sort of automated changelog in the future this is 0.101.0rc0, no? In the title of the PR :)

**Comment by samuelgarcia** [comment]
The DEV must be False in pypi release. It tell the code that for sure the install not in editable mode and then for installing SI inside conatiners then we use the pypi.
When DEV=True then can copy the sources inside the dockers.

So yes DEV=False for every release and then True just after.

**Comment by alejoe91** [comment]
@samuelgarcia DEV=False is merged. Can someone approve this so we cut the pre-release for @DradeAW ?

@zm711 @h-mayorquin

**Review by yger — APPROVED** [review]

**Review by zm711 — APPROVED** [review]

**Comment by alejoe91** [comment]
Thanks guys!

**Pull request merged**
