### PR TITLE
Add `peak_channel` as a method to `localize_peaks` in SortingComponents

### LINKED ISSUE #1089: [implementation] Implement "nearest channel" localization method
### Current issue

The current [`peak_localization`](https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/sortingcomponents/peak_localization.py) module implements the `center_of_mass` and `monopolar_triangulation` methods.
Some applications might use a very simple approach that localizes a spike/unit based on the nearest channel location.

### Proposed solution

Implement an additional `nearest_channel` method for `peak_localization`.

### ETA since in progress

1-2 weeks

### Other requirements

- [ ] Documentation
- [ ] Testing

### PR DESCRIPTION
**Pull request by h-mayorquin**
Snould close #1089 once this is done.

### CODE REVIEW

**Review by yger — APPROVED** [review]
Looks good to me, this is exactly what I had in mind

**Comment by samuelgarcia** [comment]
Hi all.
i am not sure to be happy with this idea.

We can have the same results with this

```python
chan_locs = rec.get_channel_locations()
peaks_locations = chan_locs[peaks['channel_ind']`
```
which is 1000x faster and do not need any traces loading and no parralel stuff.

**Comment by alejoe91** [comment]
@samuelgarcia if you then want the peak locations dtype you have to manually instantiate the array..while this is built-in

**Comment by alejoe91** [comment]
Maybe we can get rid of the loop?

**Comment by yger** [comment]
The plan was to start diving into the components. I thought after discussing with you that KS was using such a localization scheme, but turned out after the presentation of Alessio that this is not even the case. I just benchmarked it, and no mystery, it was worst the CoM and worst than Monopolar

**Comment by yger** [comment]
To be honest, not sure it will be used much, but it was a quick and easy start to add such a localization scheme and can be used as an example.

**Pull request merged**
