### PR TITLE
Refactor widgets

### PR DESCRIPTION
**Pull request by samuelgarcia**
Other implementation for the same idea as #682

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@magland : some work in progress push here today.
There is now 5 widgets in the new API with the mapplotlib backend.

@alejoe91 :
Normally this API do not change at all the previous bebavior. If anyone is OK, I would propose to merge this soon in the master.
So I will be able to make small progress (widget per widget) after without preventing improvement in widgets module.

**Comment by magland** [comment]
This looks great @samuelgarcia .
But I'm a little confused... is this going to break things? Are the legacy widgets still available using the same calling scheme as before? I'd suggest to preserve the old as the default, and then have some other explicit calling scheme to use the refactored widgets.

**Comment by samuelgarcia** [comment]
Normally, the legacy widgets will still be callable except for the new widgets that have been ported to the new API.
The naming and behavior will be the same for matplotlib backend so the transition will be smooth enough for the user.
And I do not stress us to move everything at once.
I just need to uncomment one import in the init.py to import all legacy functions.

**Comment by magland** [comment]
> Normally, the legacy widgets will still be callable except for the new widgets that have been ported to the new API. The naming and behavior will be the same for matplotlib backend so the transition will be smooth enough for the user. And I do not stress us to move everything at once. I just need to uncomment one import in the init.py to import all legacy functions.

Okay, that sounds good to me.

**Comment by samuelgarcia** [comment]
If tests pass : then ready to merge.

**Pull request merged**
