### PR TITLE
slurm launcher

### PR DESCRIPTION
**Pull request by samuelgarcia**
@MarineChap : I started this.
Not tested for now.
Have a look and tell me.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@MarineChap 
I tested it on my side.
It seams to work.
Have a look to spikeinterface/sorters/tests/test_launcher.py and tell if it work on your side.

**Comment by MarineChap** [comment]
Super ! Thanks for being super fast. I will test it asap.

**Comment by samuelgarcia** [comment]
I don't think I have been so fast I talking about this since 10 month!!

**Comment by MarineChap** [comment]
This work perfectly on my side ! Thanks

**Comment by samuelgarcia** [comment]
cool.

**Review by alejoe91 — APPROVED** [review]

**Pull request merged**
