### PR TITLE
Spike sorting hackathon updates

### PR DESCRIPTION
**Pull request by jsiegle**
These commits implement three main updates:

1. Methods for computing Neuropixels sample shifts and channel groups have been moved out of the SpikeGLX extractor and into a new file, called `neuropixels_utils.py`. If you know the number of channels and number of ADCs for your probe model, you can compute and apply the sample shifts like so:

```python
import spikeinterface.extractors as se
import spikeinterface.toolkit as st
sample_shifts = se.get_neuropixels_sample_shifts(num_channels=384, num_adcs=12)
R_shift = st.phase_shift(R, inter_sample_shift=sample_shifts)
```

2. Fixed a bug in the `CommonReferenceRecording` class that caused channels to be re-ordered when referencing non-consecutive groups of channels (this is commonly done for Neuropixels recordings). Instead of using `hstack`, channels are now added to the output traces in the correct locations.

3. Added a `HighpassFilterRecording` class. Even though highpass filtering can easily be accomplished with the `FilterRecording` class, I think it's important to have a dedicated class for this because bandpass filtering can remove potentially valuable info about spike waveform shape.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Josh,
this looks very good.
Thanks for caching the bug, I think it is a very old one that have been propageted here without be paying attention to theses lines.

**Comment by alejoe91** [comment]
Thanks @jsiegle 

Looks good to me too! A single suggestion: when finding an npix open-ephys probe, why not loading the sample shifts directly (similarly to SpikeGLX)?

**Comment by jsiegle** [comment]
This is definitely worth doing, but currently the only way to determine the number of ADCs per probe is via a lookup table on the part name in the settings file. We are going to add the number of ADCs to the settings files, so that number can be input directly into the phase shift/channel group methods. I can also add the lookup table for all existing part names, but I will do this in a separate pull request.

Also, I just pushed a change that ensures that the data type is preserved in the common referencing operation -- let me know if that looks ok.

**Comment by alejoe91** [comment]
@jsiegle we might need to also cast the `self.operatot_func` return to prevent dtype mismatches

**Pull request merged**
