### PR TITLE
Containerization docs

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Comment by bendichter** [comment]
to do: reformat into rst

**Comment by samuelgarcia** [comment]
Hi Ben,
thanks for this.

A small doc was already existing here : 
https://spikeinterface.readthedocs.io/en/latest/module_sorters.html#running-sorters-in-container-docker-singularity
https://github.com/SpikeInterface/spikeinterface/blob/master/doc/module_sorters.rst#running-sorters-in-container-dockersingularity

Maybe, we should delete the old one and link to this new page. What do you think ?

**Comment by vncntprvst** [comment]
I don't write permission here so I submitted edits in PR #765

**Comment by samuelgarcia** [comment]
Salut Vincent.
Merci I close this one so.

**Pull request closed without merging**
