### PR TITLE
Sphinx Fixes

### PR DESCRIPTION
**Pull request by zm711**
This is a work in progress. I was trying to build locally for to test #1964, but when I build locally it doesn't become nested. I also wanted to add some fixes--but I need to test the with rtd build rather than local for this. 

Also the build has 97 warnings. So this is working on cleaning up those warnings just so they don't potentially cause build failures in the future.

### CODE REVIEW

**Comment by alejoe91** [comment]
Thanks @zm711 

The docs build is failing. Probably need to add `ipython` in the docs requirements?

**Comment by zm711** [comment]
I'm trying just to run this through the normal sphinxext. The IPython site says to use IPython.sphinxext, but other sites say use sphinxext. I'll add IPython if this test fails.
@alejoe91

**Comment by h-mayorquin** [comment]
The docs are working on :
https://github.com/SpikeInterface/spikeinterface/pull/1992

So I am wondering what's up with this.

**Comment by zm711** [comment]
@h-mayorquin 

I am working on updating some of the sphinx stuff since currently they are written in an older format. With IPython dropping support for python 2 the docs are throwing a bunch of potential warnings for using ipython3 in the docs. They are fine for now, but I'm trying to future proof things. But just need to figure out if its a doc environment issue or something else.

**Comment by zm711** [comment]
With this PR we go from 97 warnings of mistakes down to 7.

**Comment by zm711** [comment]
Last few errors/warnings to get through... They are hard to track because rtd/sphinx doesn't use the file lines, but uses lines based on the function as line 0 or line 1.

```
/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/checkouts/1991/src/spikeinterface/preprocessing/motion.py:docstring of spikeinterface.preprocessing.motion.correct_motion:24: ERROR: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/checkouts/1991/src/spikeinterface/postprocessing/principal_component.py:docstring of spikeinterface.postprocessing.principal_component.compute_principal_components:21: WARNING: Bullet list ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/checkouts/1991/src/spikeinterface/widgets/spikes_on_traces.py:docstring of spikeinterface.widgets.spikes_on_traces.SpikesOnTracesWidget:25: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/checkouts/1991/src/spikeinterface/widgets/traces.py:docstring of spikeinterface.widgets.traces.TracesWidget:102: WARNING: Inline strong start-string without end-string.
/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/checkouts/1991/src/spikeinterface/sortingcomponents/peak_detection.py:docstring of spikeinterface.sortingcomponents.peak_detection.detect_peaks:151: CRITICAL: Unexpected section title or transition.
```

**Comment by zm711** [comment]
So I was able to get the warnings down to this one, but for the life of me I can't fix this:

```
/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/checkouts/1991/src/spikeinterface/widgets/traces.py:docstring of spikeinterface.widgets.traces.TracesWidget:102: WARNING: Inline strong start-string without end-string.
```

**Comment by samuelgarcia** [comment]
Hi Zach.
one comments and one question.

`spikeinterface/doc/how_to/` folder is locally generated from `/examples/how_to/`. See this readme
https://github.com/SpikeInterface/spikeinterface/tree/main/examples/how_to

What is the benefit/cost of installing iptyhon for doc ? iptyhon is quite a big stuff no ?
We are still using readthedoc which is quite slow to build env. The less package we have the faster documentation builds.

**Comment by zm711** [comment]
@samuelgarcia 

It's how the docs are written. We could convert all the ipython docs to pure python docs for the examples if you don't want to install. Technically the `ipython3` directive was not really supported by rtd, but it was still forcing it to build with a warning. 

I could switch this to be all python instead and delete the ipython to the docs?

**Comment by zm711** [comment]
> spikeinterface/doc/how_to/ folder is locally generated from /examples/how_to/. See this readme
https://github.com/SpikeInterface/spikeinterface/tree/main/examples/how_to

I always forget that. Sorry.

**Comment by alejoe91** [comment]
> So I was able to get the warnings down to this one, but for the life of me I can't fix this:
> 
> ```
> /home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/checkouts/1991/src/spikeinterface/widgets/traces.py:docstring of spikeinterface.widgets.traces.TracesWidget:102: WARNING: Inline strong start-string without end-string.
> ```

Can you try to add a new line before the first item here? https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/widgets/traces.py#L29

A few months ago I also spent some time trying to fix sphinx warnings..not the smoothest thing to do!

**Comment by zm711** [comment]
@alejoe91,

That didn't work locally.

**Comment by zm711** [comment]
> We are still using readthedoc which is quite slow to build env. The less package we have the faster documentation builds.
@samuelgarcia 
Also without ipython for recent builds, 1 took ~500 seconds and one took ~600 seconds. And with ipython the builds are taking about ~600 seconds. So it doesn't seem to change the speed too much.

**Comment by samuelgarcia** [comment]
@zm711 thank you for checking the speed. So lets keep iptyhon in doc dependencies.
I was not awre of that ipython directive not working. This was generating during the conversion from the local notebook maybe we can convert using others options to void this. No ?

**Comment by zm711** [comment]
@samuelgarcia,

RTD still renders it, but it warns with this:

`WARNING: Pygments lexer name 'ipython3' is not known`

RTD/Sphinx must be falling back to `parsed-literal` or `python` to create the file, but it would be better to use a supported format in case there is an update to Sphinx or RTD (although they are currently pinned someone may decide to unpin them in the future) so that they don't all fall apart in the future.

I don't use the converter much so I'm not sure. A quick google showed you could use other formats, but I'm not sure how to fine tune that.

**Comment by h-mayorquin** [comment]
Thanks a lot for taking a time to do this, also for fixing some of the references.

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
@zm711 is it ready to review? Looking great on my side! :)

**Comment by zm711** [comment]
Yep all ready. I was actually just waiting to see if Sam wanted anything, but this can be merged as is (after your review :) )

**Comment by alejoe91** [comment]
@zm711 the last error intrigued me...it was hard to find but basically the `TracesWidgets` was the only one to have a `Returns`, so to addition of backends + backend_kwargs would add parameters after the Returns in the docstring. I moved the `Returns` in the automatic docstring generation in the `widgets_list.py`, so that all `plot_*` functions have a `Returns` (`BaseWidget`)!

**Comment by zm711** [comment]
@alejoe91,

I'm happy it intrigued you! It drove me crazy. I line edited the docstring with no success. But people complain that sphinx+ numpydoc can jump around like that a bit so they can be hard to debug.

**Comment by alejoe91** [comment]
> @alejoe91,
> 
> I'm happy it intrigued you! It drove me crazy. I line edited the docstring with no success. But people complain that sphinx+ numpydoc can jump around like that a bit so they can be hard to debug.

"a bit" is an understatement :P

**Pull request merged**
