### PR TITLE
add hs_detection as sorting component

### PR DESCRIPTION
**Pull request by lkct**
algorithm implementation in [hs-detection](https://github.com/lkct/hs-detection)

### CODE REVIEW

**Comment by mhhennig** [comment]
Just to add some context: This wraps the detection algorithm used in Herding Spikes. It depends on a standalone implementation that's available via pypi. It is fast and parallel, and we'll evaluate/compare performance soon.

**Comment by mhhennig** [comment]
Just noticed: The unit tests use Python 3.8, but the new hs-detection package uses 3.9 features. Will it be kept at 3.8 for now, what's the plan?

**Comment by alejoe91** [comment]
> Just noticed: The unit tests use Python 3.8, but the new hs-detection package uses 3.9 features. Will it be kept at 3.8 for now, what's the plan?

@mhhennig is there a reason why 3.8 is not supported on the hs-detection side?

**Comment by lkct** [comment]
> > Just noticed: The unit tests use Python 3.8, but the new hs-detection package uses 3.9 features. Will it be kept at 3.8 for now, what's the plan?
> 
> @mhhennig is there a reason why 3.8 is not supported on the hs-detection side?

@alejoe91 cc @mhhennig 
We decided at the beginning that the hs-detection package would be based on py3.9 for some new features, and we expect 3.9+ will be majorly used in the following. I've just addressed the issues blocking the tests, so it works (at least with the test setting) on 3.8 now. However, I don't think it's worth enforcing full compatibility to 3.8, involving more code changes and giving up new features.

**Comment by alejoe91** [comment]
@mhhennig @lkct 

Closing this for the moment. Let's discuss over a new PR

**Pull request closed without merging**
