### PR TITLE
Improvement to `get_empty_units()`

### PR DESCRIPTION
**Pull request by DradeAW**
`sorting.remove_empty_units()` can be very slow when the spike trains aren't cached

I propose to call `count_num_spikes_per_unit()` which is already optimized.
The downside is that it will not remove a unit that is empty in one segment but not empty in another. Is this a problem?

### CODE REVIEW

**Comment by samuelgarcia** [comment]
I think "empty" means zeros spike in all segments. No ?

**Comment by alejoe91** [comment]
> I think "empty" means zeros spike in all segments. No ?

Agreed

**Comment by DradeAW** [comment]
Then this PR also fixes that :)

**Comment by zm711** [comment]
Would it be beneficial to put that into a docstring then? So that users can see that the definition of empty is zero spikes in all segments. I would agree that makes for a fair definition, but I can imagine a user attempting to use this function and thinking it is an 'any' style and not an 'all' style.

**Comment by zm711** [comment]
Thanks @DradeAW :)

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
Good to merge for me. @samuelgarcia wanna take a look?

**Review by samuelgarcia — APPROVED** [review]

**Pull request merged**
