### PR TITLE
Robust method for checking gpu-nvidia availability

### PR DESCRIPTION
**Pull request by h-mayorquin**
This is related to #705 and once we are done with this it probably should be closed.

This method works on dandi-hub when I tested it a while ago, the only problem is that it requires a dependency:
https://nvidia.github.io/cuda-python/overview.html

I am also not sure how to add this as a dependency.

What do you think?

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
> This method works on dandi-hub when I tested it a while ago, 

@h-mayorquin Do you mean, with this fix, it would be possible to run a spike sorter that requires an 'NVIDIA GPU' on the T4 GPU instance from the DANDI Hub?

**Comment by alejoe91** [comment]
I would be in favor of adding it to the `full` install, since it's really useful. @samuelgarcia do you agree?

**Comment by samuelgarcia** [comment]
I am not super warn to had too much package in the full.
Maybe we are nto aligned, but for me "full" is more or less "main" (and maybe should be renamed) = main package super well maintain and that evrybody have more or less already.
So I have the tendency to limit as much as possible what is in the full to avoid dependency blowing
For me testing the GPU ability is at the moment a bit in the corner and mainly for sortingcomponents.
Maybe we could: 
  * rename "full" to "main" and keep it little
  * have a "internal_sorter" section that ould have cude/torch/pymde/... which are more specific.

All external sorter are super super hard to installed in the same env as SI mainly for dependency graph so we have to be carfull. No ?

**Comment by alejoe91** [comment]
@samuelgarcia the way we check for GPU availability right now fails on systems that do not have access to the `nvidia-smi` command (e.g. dandihub). This prevents running GPU-based external sorters on those machines. 

Therefore, I think this needs to be a `full` requirement, since it mainly affects the `sorters` module (which is a `main` module)

**Review by alejoe91 — APPROVED** [review]

**Comment by h-mayorquin** [comment]
> > This method works on dandi-hub when I tested it a while ago,
> 
> @h-mayorquin Do you mean, with this fix, it would be possible to run a spike sorter that requires an 'NVIDIA GPU' on the T4 GPU instance from the DANDI Hub?

@CodyCBakerPhD sorry for not answering before, this escaped me. What I meant is that the method correctly told me I had cuda when I tried it a while ago. I have not tested that the sorters can be run there. I will run them and come back to you.

**Pull request merged**
