### PR TITLE
Added some typing in `BaseExtractor`

### PR DESCRIPTION
**Pull request by DradeAW**
I figured since this is kind of the 'root' class, it needed some typing.

I didn't put them all, but there are several.
Feel free to add more if you want.

### CODE REVIEW

**Comment by DradeAW** [comment]
I was thinking also: we could make `ID_Type = Union[int, str]`, a type dedicated to what `unit_id` and `channel_id` can be.

That way if we want to add a new accepted type for ids, we can change just `ID_Type` and it will propagate.

What do you think?

**Comment by DradeAW** [comment]
> you have a phd manuscript to write you not waste your time on python typing. Life is short.

I agree it's not the most effective use of my time, but my brain just needs the details to be right or I'll feel like I'm doing bad work ^^'

**Comment by h-mayorquin** [comment]
Hey, @DradeAW.
See this first:
https://github.com/SpikeInterface/spikeinterface/issues/1432

Now on the subject matter. In general, I prefer to not have indirection for such a small collection of types. We have a `FolderPathType = TypeVar("FolderPathType", str, Path)` in another project and I find it annoying. I need to remember where to import this specific type so it gets on my way when I am coding. In this case I find `channel_ids: Union[str, int]` clear enough. 

Finally, I think I prefer the notation introduce in [PEP 604](https://peps.python.org/pep-0604/) which makes this even less verbose `str | int` (this can be enabled pre python 3.10 by using `[from __future__ import annotations]`.

**Comment by DradeAW** [comment]
> Finally, I think I prefer the notation introduce in [PEP 604](https://peps.python.org/pep-0604/) which makes this even less verbose `str | int` (this can be enabled pre python 3.10 by using `[from __future__ import annotations]`.

I prefer it too (and use it in my own code)!
But my understanding was that it was introduced in Python 3.9, and thus not compatible with Python 3.8? (which SpikeInterface uses).

I personally don't like using `channel_ids: str | int` because what if, in the future, we decide that another type can represent channel_ids? We can't change the type everywhere, it would be too much work.

But if the plan is to switch to `str` in the future, then we can just wait until this is done :)

I'm just worried about the "under the hood" conversion to str: then if I give `unit_ids` to the sorting with integers, then `sorting.unit_ids == unit_ids --> False`

**Comment by h-mayorquin** [comment]
Using `from __future__ import annotations.` will allow you tu use the short notation for python 3.8 and 3.9. 

```
I personally don't like using channel_ids: str | int because what if, in the future, we decide that another type can represent channel_ids? We can't change the type everywhere, it would be too much work.
```

This is a good point that it is good to have a centralized defintion. However, good IDEs should make the refactoring of this type of code easy. If the typing were a little bit more complicated or it was more likely to change it would move me in your direction, though.

**Review by samuelgarcia — APPROVED** [review]

**Pull request merged**
