### PR TITLE
Apply black

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
no comments.

**Comment by alejoe91** [comment]
Camarade, let pre-commit do it!

**Comment by CodyCBakerPhD** [comment]
> Camarade, let pre-commit do it!

Looks like his personal fork (or this PR) didn't give permissions to the bot: https://results.pre-commit.ci/run/github/196581117/1707761650.OH4oytBmQWSPClvI85Ympw

**Comment by samuelgarcia** [comment]
héhé!

**Pull request merged**
