### PR TITLE
fix compute_matching_matrix

### PR DESCRIPTION
**Pull request by samuelgarcia**
@alejoe91 @h-mayorquin 
A quick and very urgent fix before the webinar next Tuesday.

### CODE REVIEW

**Comment by alejoe91** [comment]
Thanks camarade! I'll run the tutorial on my side and we can release a patch on monday

**Comment by h-mayorquin** [comment]
What was failing? Any example so I can build a non-regression test?

**Comment by samuelgarcia** [comment]
Hi Ramon.
I you run this tutorial : https://github.com/SpikeInterface/spiketutorials/tree/master/Official_Tutorial_SI_0.99_Nov23
The section "9. Spike sorting comparison" give a total blank agreement matrix.
You can download the dataset on the link.

It took some time to discover that the index2 have to be moved when no match.
When doing this simple patch the matrix looks like the old one but I am not 100% sure that this is correct.
I think to reproduce this we need a case where the index1 is advancing and the index2 is left behind or something like that.

**Comment by h-mayorquin** [comment]
Let me take a look! I have two hours before the next person comes to see the house.

**Comment by h-mayorquin** [comment]
@samuelgarcia 
I can't run the full tutorial, I don't have the files for running kilosort 2 locally and the oen from docker is telling me - wrongly, I think- that I don't have the required nvidia. 

I think it is easier if you send me the pickled sorters by slack then I can track the nature of the bug.

Also, I have no idea why the full tests are failing but I ran the comparison tools tests locally in this branch and they are passing.


What do you think of just reverting the function for the release to the old version. I left the basic components still there:

https://github.com/SpikeInterface/spikeinterface/blob/f725a406f3cc16452636f5bf0652a5d541571be2/src/spikeinterface/comparison/comparisontools.py#L8-L37

I fixed some of the bugs that the old function had but it seems that I introduced some others. We can then fix the other bugs post-release.

**Comment by h-mayorquin** [comment]
But by the way if you feel confident that this is a good fix feel free to merge. I just think that is less safe than either releasing with the old version or having two people understand the nature of the bug (I can't not really understand it by looking at the diff).

**Comment by alejoe91** [comment]
@h-mayorquin I can send you the sortings

**Pull request closed without merging**
