### PR TITLE
update set_kilosort2_path to set_kilosort2_5_path

### PR DESCRIPTION
**Pull request by JoeZiminski**
I believe the API for Kilosort2.5 is `.set_kilosort2_5_path()` rather than `.set_kilosort2_5_path()`

### CODE REVIEW

**Comment by h-mayorquin** [comment]
Hi, thanks for the PR.  

This Friday 2023-04-07 we will be changing the default branch from master to main. So new PRs from now on should be branched from main instead of master. Moreover, the new branch main has a [ src package structure](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/) so any changes in code should start from it.

When you open a PR you can chose the base here:
image

After Friday this will be done automatically.

**Review by h-mayorquin — CHANGES_REQUESTED** [review]
I have sent the contents of the PR to the main branch here:

#1482

**Comment by JoeZiminski** [comment]
Great thanks @h-mayorquin! will make sure to bear that in mind for future PR

**Comment by alejoe91** [comment]
Thanks @JoeZiminski and @h-mayorquin 

Closing this then

@JoeZiminski we'll set the default branch to main on Friday ;)

**Pull request closed without merging**
