### PR TITLE
Allow any filter in spikeinterface

### PR DESCRIPTION
**Pull request by ferchaure**
Just a WIP to discuss. related to #363 
I guess this is the simplest change to allow any filter in spikeinterface

I don't know the details of self._kwargs, should I create the dict with only the used inputs inside the if statement? (discarting filter_order, band, etc and adding coef) or just adding coeff to the current line?

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi. Thank you for this.

You also need to to put `coef` in self._kwargs for the dump system in SI.

**Comment by ferchaure** [comment]
Fixes done, 
What happened with the filtering using FFT? Just to know if it has to be implemented (maybe I can help) or was just discarded in the new version.

**Comment by samuelgarcia** [comment]
FFT have been discard in the new version.
If really needed this could be added back but the implementation is not easy because the chunking is not known in advance (at the init) but when we process (.save())

_kwargs is the internal dict used to dump to json or dict for parralell processing.
The tricky think is that it has to be compatible with json and so numpy stuuf need to be converted as list.

Maybe you can test dump/load cycle with coeef to test this.

**Comment by ferchaure** [comment]
done, I guess that I understand the _kwargs a bit better now.

About the FFT filters I was realising that issue as well, tricky stuff. An alternative could be define the FFT filter using a function f(w) that define the values for any frequency.  But it will have a high error if the chunk is too small  (or the function has fast changes). 
Is there a minimum chunk size that can be changed for filtered data? I'm thinking that even classic filters can have issues if the chunk is really small.

**Comment by samuelgarcia** [comment]
Yes you are right, even in time domain chunking lead to erros on border this is why we have  `margin_ms=5.0`.
So unless the chunking is smaler than the border it should be OK for high pass filter.
For low pass chunking is not possible.

**Comment by ferchaure** [comment]
I'm not sure which are the real practical advantages of the FFT filter, but if It's really needed I can try to make it work. 
Probably adding a check that warns the user that the error could be quite high taking the worst case of  just margin_ms frames.

About this pull request... notice that with this changes the filter coefficients are saved in the dump file, in all the cases. Then they are not recomputed again after loading. Maybe you prefer a more complex implementation like adding a new 'custom' btype in the filter inputs and/or only saving the coefficients if they are custom made.

**Comment by alejoe91** [comment]
@ferchaure I think you can easily solve the last point by setting `self._coeff` (or another variable) and propagate it to the segments, while adding the original `coeff` to the `_kwargs` (so if it's None, the coeff are not dumped)

**Comment by ferchaure** [comment]
Done :+1:

**Review by alejoe91 — APPROVED** [review]

**Comment by samuelgarcia** [comment]
This looks good also to me.
Could you add one small test in test_filter.py about this case ?

**Comment by alejoe91** [comment]
> This looks good also to me. Could you add one small test in test_filter.py about this case ?

Second that!

**Comment by ferchaure** [comment]
done

**Comment by alejoe91** [comment]
@samuelgarcia can we merge?

**Comment by samuelgarcia** [comment]
Perfect.
Thanks a lot.

**Pull request merged**
