### PR TITLE
Fix hdbascan installation in read the docs

### PR DESCRIPTION
**Pull request by alejoe91**
Try to fix docs run

### CODE REVIEW

**Comment by h-mayorquin** [comment]
Sorry, I misread you in the other thread, you are proposing a higher bound, I think the problem is the lack of a lower bound. Another option is to put an upper bound (ceiling) on hdbscan.

But probably the easier is just to instead send the hdbscan isntall to the conda file and the figure out this later.

**Comment by alejoe91** [comment]
or installing hdbscan with conda ;)

**Comment by h-mayorquin** [comment]
Probably the canary in the mine of the problems that came after.

**Comment by alejoe91** [comment]
> Probably the canary in the mine of the problems that came after.

Definitely! The release rush made us oversee this!

**Pull request merged**
