### PR TITLE
Propagate "load_sync_channel" args to spikeinterface.

### PR DESCRIPTION
**Pull request by samuelgarcia**
Propagate "load_sync_channel" args to spikeinterface.
And also remove HAVE_NEO_10_2 because it is a mandatory dep.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@MarineChap

**Comment by samuelgarcia** [comment]
@LiesDec : here the ability to load the synch channel.
I will also push some utils function to compute the synchro with linear regression

**Comment by MarineChap** [comment]
Hello, I did not test it yet but this is a modif only for spikeglx right? because we are working with open-ephys now.

**Comment by MarineChap** [comment]
I don(t know the exact detail of the problem. But here is the issue where Lies was explaining the error she gets when she try to load the sync saved as a 385e channel. 
https://github.com/SpikeInterface/probeinterface/issues/113

**Review by alejoe91 — APPROVED** [review]

**Comment by samuelgarcia** [comment]
@alejoe91 : have a look.
ready to merge on my side if pass tests

**Pull request merged**
