### PR TITLE
Fix version in xfail test_run_sorter (>3.12 --> >=3.12)

### PR DESCRIPTION
**Pull request by alejoe91**
@h-mayorquin here it is!

### CODE REVIEW

**Review by h-mayorquin — APPROVED** [review]
Is that something that threadpool is working on solving? Should we keep track of something to remove this or do we expect that this won't ever work on python latest version on windows?

**Comment by alejoe91** [comment]
actually, the previous PR ran all tests fine, so it might be fixed already???

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikeinterface/actions/runs/9694881804/job/26753475352

**Comment by h-mayorquin** [comment]
Should we keep this open a bit to test if this is the case?

This was the error for reference:
https://github.com/SpikeInterface/spikeinterface/actions/runs/9693230325/job/26748253219?pr=3090

**Comment by zm711** [comment]
Is this good? Or should be closed? I didn't follow the error, but it has been a month with multiple PRs without this and things seem to be working?

**Comment by h-mayorquin** [comment]
It has not appeared again so maybe...?

**Comment by alejoe91** [comment]
Closing!

**Pull request closed without merging**
