### PR TITLE
Remove lack of units in NeoBaseExtractors

### PR DESCRIPTION
**Pull request by h-mayorquin**
This output to standard output is causing problems in some of our doctests in:

https://github.com/catalystneuro/nwb-conversion-tools/pull/573

I think that this code serves not purpose. The user of a recording interface does not have a way to change the units. I think this information is useful for developers but as it stands I think it could be replaced by appropriate notes in the corresponding extractor or back in neo.

What do you think, @samuelgarcia?

To describe the problem in more detail look at the following example:

```python
from pathlib import Path
from spikeinterface.extractors import SpikeGadgetsRecordingExtractor
import spikeextractors as se

DATA_PATH = Path("/home/heberto/ephy_testing_data/")
file_name = "W122_06_09_2019_1_fromSD"
file_path=DATA_PATH / "spikegadgets" / f"{file_name}.rec"

recorder = SpikeGadgetsRecordingExtractor(file_path=file_path, stream_id="trodes")
```
Output:
```
This extractor based on  neo.SpikeGadgetsRawIO have strange units not in (V, mV, uV) ['' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''
 '' '' '' '' '' '' '' '']
```

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Lets go for midterm directly, no ?

**Comment by h-mayorquin** [comment]
> Lets go for midterm directly, no ?

I can do it in this PR. 
Whata bout the error, @samuelgarcia ? Any ideas?

**Comment by h-mayorquin** [comment]
@samuelgarcia 
I implemented the short term fix here. The middle term should be implemented in #761. Maybe we can merge this as I need it and then fine tune with the other PR.

**Review by samuelgarcia — APPROVED** [review]

**Comment by samuelgarcia** [comment]
done . Thanks.

**Pull request merged**
