### PR TITLE
Set paths in kwargs for neo extractors as str of the absolute paths

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Why do we need need this absolute path in kwargs ?
A script + dataset will not be portable if we copy to another disk.

**Comment by alejoe91** [comment]
@samuelgarcia that's why we made the `relative_to` mechanism. I added this because some paths were saves as pathlib objects. I think it's better to have absolute paths in general

**Comment by samuelgarcia** [comment]
OK

**Review by samuelgarcia — APPROVED** [review]

**Comment by samuelgarcia** [comment]
Alessio please work on your fork!! don't make branch here!!!

**Pull request merged**
