### PR TITLE
Port bug fix PRs from Main over to 0.100-bug-fixes

### PR DESCRIPTION
**Pull request by zm711**
PRs #2701 , #2690, #2716

Were there any other that we needed to port over?

### CODE REVIEW

**Comment by alejoe91** [comment]
I think it's good! Maybe let's make a new 0.100.6 release? @zm711 do you mind if I push here release notes and version bump?

**Comment by zm711** [comment]
Yeah sure. Works for me!

**Comment by zm711** [comment]
Don't merge until we decide on solution for #2710 (side left might be wrong strategy).

**Comment by zm711** [comment]
Forgot to update `has_exceeding_spikes`. This has now been patched here!

**Comment by luiztauffer** [comment]
@zm711 can we have this merged? It would be helpful for me

**Comment by zm711** [comment]
Hey @luiztauffer! I think @alejoe91 was deciding whether to add release notes to this PR. It's ready on my side (although there is another issue with KS4 that we might want to package first #2742).

**Pull request merged**
