### PR TITLE
Add zarrrecordingextractor.py for backward compatibility

### PR DESCRIPTION
**Pull request by alejoe91**
Plus some default values in common ref docstrings

### CODE REVIEW

**Review by h-mayorquin — APPROVED** [review]
Is this for someone importing zarr recording extractor directly from the old file:

```
from spikeinterface.core.zarrrecordingextractor import ZarrRecordingExtractor
```
?

**Comment by alejoe91** [comment]
Indeed. This is a case when a user saved a JSON or pickle file before the refactoring and then uses `load_extractor`, which tries to instantiate the `spikeinterface.core.zarrrecordingextractor.ZarrRecordingExtractor`

**Comment by h-mayorquin** [comment]
Thanks for the info.

**Comment by samuelgarcia** [comment]
ok.

**Pull request merged**
