### PR TITLE
working combinato sorter

### PR DESCRIPTION
**Pull request by ferchaure**
Hi Guys, working code for combinato

But only return units not labelled as artifacts or outliers/not sorted... do you think that we should define a common property with defined categories? or maybe multiple binary ones

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Fernando.
Looks good. Tell me when I can merge.

**Review by samuelgarcia — APPROVED** [review]

**Comment by ferchaure** [comment]
The issue is how to return the units labelled as artifacts or outliers/not sorted, What do you think about returning all the units with the boolean properties: "unsorted" and "artifact".... maybe is better that way because some sorters could sort artifacts just in case

**Comment by samuelgarcia** [comment]
There is no fixed convention in spikeinterface for properties after sorting at the moment.
boolean property is OK.
str property with an easy to read label is also OK.
I would go for string "unsorted"/"artifact".

Note that properties are now in new SI a numpy array. So it can be bool or str without problem.
In both case it is easy to slice with `BaseSorting.select_units(unit_ids)`

**Comment by ferchaure** [comment]
I like the idea of boolean properties: "unsorted" and "artifact". I could use the "unsorted" for waveclus as well. We should make a convention, It will help a lot to comparing between sorters without reading all the documentations of each one.

**Comment by samuelgarcia** [comment]
OK lets start with boolean in combinato and waveclust.
A pro for boolean is that we can combine property with OR/AND to select units.
Tell when I can merge this.

**Comment by ferchaure** [comment]
done

**Pull request merged**
