### PR TITLE
Fix KS2/2.5/3 skip_kilosort_preprocessing

### LINKED ISSUE #3263: Sorting in docker with kilosort 2 or 4 fails
Sorting in docker fails with Kilosort 2 or 2.5 when running it on tetrode grouped, bandpassed, rereferenced, whitened data, although it works fine with other sorters, including tridesclous and mountainsort4. A 10 minutes slice of the data is used with `BaseRecording.get_traces()`.

```python
    params = {'skip_kilosort_preprocessing': True, 
              'car': False,
              'delete_tmp_files': True}
    sorting = ss.run_sorter_by_property(sorter_name=sorter,
                                        recording=recording_preprocessed,
                                        grouping_property='group',
                                        folder=sorter_fp,
                                        docker_image=True,
                                        verbose=True,
                                        **params)
```

```python
SpikeSortingError: Spike sorting in docker failed with the following error:
/Users/systemses/Downloads/data_analysis/data/MD-mPFC-Exp/MD-mPFC-1_2024-07-04_11-17-12/Record Node 106/experiment1/recording1/spike_sorting/kilosort2_output/in_container_sorter_script.py:23: DeprecationWarning: `output_folder` is deprecated and will be removed in version 0.103.0 Please use folder instead
  sorting = run_sorter_local(
Traceback (most recent call last):
  File "/Users/systemses/Downloads/data_analysis/data/MD-mPFC-Exp/MD-mPFC-1_2024-07-04_11-17-12/Record Node 106/experiment1/recording1/spike_sorting/kilosort2_output/in_container_sorter_script.py", line 23, in <module>
    sorting = run_sorter_local(
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 275, in run_sorter_local
    SorterClass.setup_recording(recording, folder, verbose=verbose)
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 233, in setup_recording
    cls._setup_recording(recording, sorter_output_folder, sorter_params, verbose)
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/external/kilosortbase.py", line 148, in _setup_recording
    padded_recording = TracePaddedRecording(
TypeError: __init__() got an unexpected keyword argument 'parent_recording'
```

And in Kilosort 4

```python
    params = {'skip_kilosort_preprocessing': True,
              'do_CAR': False,
              'do_correction': False}
```

Runtime trace:
```python
{
    "sorter_name": "kilosort4",
    "sorter_version": "4.0.12",
    "datetime": "2024-07-29T08:22:40.976628",
    "runtime_trace": [],
    "error": true,
    "error_trace": [
        "Traceback (most recent call last):",
        "  File \"/root/.local/lib/python3.11/site-packages/spikeinterface/sorters/basesorter.py\", line 261, in run_from_folder",
        "    SorterClass._run_from_folder(sorter_output_folder, sorter_params, verbose)",
        "  File \"/root/.local/lib/python3.11/site-packages/spikeinterface/sorters/external/kilosort4.py\", line 261, in _run_from_folder",
        "    st, tF, _, _ = detect_spikes(ops, device, bfile, tic0=tic0, progress_bar=progress_bar)",
        "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/kilosort/run_kilosort.py\", line 481, in detect_spikes",
        "    st0, tF, ops = spikedetect.run(ops, bfile, device=device, progress_bar=progress_bar)",
        "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/kilosort/spikedetect.py\", line 204, in run",
        "    ops['wPCA'], ops['wTEMP'] = extract_wPCA_wTEMP(",
        "                                ^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/kilosort/spikedetect.py\", line 72, in extract_wPCA_wTEMP",
        "    model = TruncatedSVD(n_components=ops['settings']['n_pcs']).fit(clips)",
        "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/decomposition/_truncated_svd.py\", line 208, in fit",
        "    self.fit_transform(X)",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py\", line 313, in wrapped",
        "    data_to_wrap = f(self, X, *args, **kwargs)",
        "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/base.py\", line 1473, in wrapper",
        "    return fit_method(estimator, *args, **kwargs)",
        "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/decomposition/_truncated_svd.py\", line 228, in fit_transform",
        "    X = self._validate_data(X, accept_sparse=[\"csr\", \"csc\"], ensure_min_features=2)",
        "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/base.py\", line 633, in _validate_data",
        "    out = check_array(X, input_name=\"X\", **check_params)",
        "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
        "  File \"/home/miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py\", line 1082, in check_array",
        "    raise ValueError(",
        "  ValueError: Found array with 0 sample(s) (shape=(0, 61)) while a minimum of 1 is required by TruncatedSVD."
    ],
    "run_time": null
}
```

### PR DESCRIPTION
**Pull request by alejoe91**
Fixes #3263

### CODE REVIEW

**Comment by alejoe91** [comment]
@zm711 a leftover parent ;)

**Comment by zm711** [comment]
Those parents never let the kids have any fun....

**Review by zm711 — APPROVED** [review]

**Comment by Djoels** [comment]
I'm getting this error when running KS2.5 from docker mode, does this mean that the docker image is still on the old version? or is it a spikeinterface wrapper issue and do I just update the spikeinterface source in the docker differently?

Also: I read somewhere it doesn't really affect anything if you run kilosort processing multiple times? So as a workaround I could leave it to the default value?

**Comment by JoeZiminski** [comment]
Hey @Djoels, what is the error that you are getting / what spikeinterface version are you using? To be sure, you can delete your downloaded image and then SI will pull the latest version, just in case an older one is saved locally.

It depends on the preprocessing steps, if CAR and bandpass filter have already been applied in spikeinterface, then re-applying them in kilosort (if the filter bounds are wider) should not have much of an affect. You can actually turn of CAR in kilosort too. But for motion correction and whitening, it is not a good idea to re-apply these if they have already been applied in SI.

**Comment by Djoels** [comment]
Hi, 
I stopped all running containers referencing the image and removed the image, the new image was being pulled and it did also result in the error above: 
```
installation_mode='auto' switching to installation_mode: 'github'
Docker: pulling image spikeinterface/kilosort2_5-compiled-base
Starting container
Installing spikeinterface with github in container
Running kilosort2_5 sorter inside spikeinterface/kilosort2_5-compiled-base
Stopping container
2024-09-13 14:48 - root         - ERROR    - Error occured during sorting: Spike sorting in docker failed with the following error:
/mnt/batch/tasks/shared/LS_root/mounts/clusters/verpla38-v100-hs/code/Users/verpla38/data/hybrid-gt/2023-0502_Ctl653xrep/Sparrow User-P220081-D11-J3-12_09_2023-11_09_17.sparrowdata/hybridgt_20240816/in_container_sorter_script.py:23: DeprecationWarning: `output_folder` is deprecated and will be removed in version 0.103.0 Please use folder instead
  sorting = run_sorter_local(
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/verpla38-v100-hs/code/Users/verpla38/data/hybrid-gt/2023-0502_Ctl653xrep/Sparrow User-P220081-D11-J3-12_09_2023-11_09_17.sparrowdata/hybridgt_20240816/in_container_sorter_script.py", line 23, in <module>
    sorting = run_sorter_local(
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 275, in run_sorter_local
    SorterClass.setup_recording(recording, folder, verbose=verbose)
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 233, in setup_recording
    cls._setup_recording(recording, sorter_output_folder, sorter_params, verbose)
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/external/kilosortbase.py", line 148, in _setup_recording
    padded_recording = TracePaddedRecording(
TypeError: __init__() got an unexpected keyword argument 'parent_recording'
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/verpla38-v100-hs/code/Users/verpla38/ai-boc/src/hpoptuna.py", line 336, in main
    scores = _run_sorter(
             ^^^^^^^^^^^^
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/verpla38-v100-hs/code/Users/verpla38/ai-boc/src/hpoptuna.py", line 138, in _run_sorter
    sorting = ss.run_sorter(sorter_name=sorter,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/azureml_py312/lib/python3.12/site-packages/spikeinterface/sorters/runsorter.py", line 210, in run_sorter
    return run_sorter_container(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda/envs/azureml_py312/lib/python3.12/site-packages/spikeinterface/sorters/runsorter.py", line 663, in run_sorter_container
    raise SpikeSortingError(f"Spike sorting in {mode} failed with the following error:\n{run_sorter_output}")
spikeinterface.sorters.utils.misc.SpikeSortingError: Spike sorting in docker failed with the following error:
/mnt/batch/tasks/shared/LS_root/mounts/clusters/verpla38-v100-hs/code/Users/verpla38/data/hybrid-gt/2023-0502_Ctl653xrep/Sparrow User-P220081-D11-J3-12_09_2023-11_09_17.sparrowdata/hybridgt_20240816/in_container_sorter_script.py:23: DeprecationWarning: `output_folder` is deprecated and will be removed in version 0.103.0 Please use folder instead
  sorting = run_sorter_local(
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/.../in_container_sorter_script.py", line 23, in <module>
    sorting = run_sorter_local(
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/runsorter.py", line 275, in run_sorter_local
    SorterClass.setup_recording(recording, folder, verbose=verbose)
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/basesorter.py", line 233, in setup_recording
    cls._setup_recording(recording, sorter_output_folder, sorter_params, verbose)
  File "/root/.local/lib/python3.9/site-packages/spikeinterface/sorters/external/kilosortbase.py", line 148, in _setup_recording
    padded_recording = TracePaddedRecording(
TypeError: __init__() got an unexpected keyword argument 'parent_recording'
```

I use the settings you mentioned: 
```
"skip_kilosort_preprocessing": True,
"do_correction": False,
"car": False
```

I'm starting from a previously KS2.5 preprocessed temp_wh.dat file (which also served for curating with Phy), so these settings should be correct?
Either way, the bug with this setting doesn't seem to be fixed in the image or I'm somehow installing spikeinterface incorrectly into the docker? This should be version 0.101.0

```
installation_mode='auto' switching to installation_mode: 'github'
Docker: pulling image spikeinterface/kilosort2_5-compiled-base
Starting container
Installing spikeinterface with github in container
```

**Comment by alejoe91** [comment]
Hi, the change that fixes it is not released yet, but we have a patch release almost ready that should be done on Monday

**Pull request merged**
