### PR TITLE
Add possibility to use custom neo classes with NeoBaseExtractor

### PR DESCRIPTION
**Pull request by JulesLebert**
I am using custom Neo classes to load my data (https://neo.readthedocs.io/en/stable/io_developers_guide.html) and this commit would allow to pass the custom Neo class directly to NeoBaseRecordingExtractor (I haven't tested for NeoBaseSortingExtractor). It's useful when working with custom Neo classes and spikeinterface.

Example of how this can be used here https://github.com/JulesLebert/spikesorting_scripts/blob/main/spikesorting_scripts/io/customtdtrecording_extractor.py

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Jules,
thanks for this.
Does the to_from/from_dict working for parralell computing wiwth this patch ?

What format you have  ? Maybe a PR into neo could be also cool.

**Comment by alejoe91** [comment]
> Hi Jules, thanks for this. Does the to_from/from_dict working for parralell computing wiwth this patch ?
> 
> What format you have ? Maybe a PR into neo could be also cool.

@JulesLebert can you try the following to test whether parallel processing is working?

```
recording_custom = read_custom_tdt("tdt-folder")

rec = recording_custom.save(folder="test", n_jobs=4, chunk_duration="0.5s", progress_bar=True)
```


```

**Comment by JulesLebert** [comment]
> > Hi Jules, thanks for this. Does the to_from/from_dict working for parralell computing wiwth this patch ?
> > What format you have ? Maybe a PR into neo could be also cool.
> 
> @JulesLebert can you try the following to test whether parallel processing is working?
> 
> ```
> recording_custom = read_custom_tdt("tdt-folder")
> 
> rec = recording_custom.save(folder="test", n_jobs=4, chunk_duration="0.5s", progress_bar=True)
> ```

Parallel doesn't work when I try this. I have TDT data that couldn't be loaded with the tdtio from Neo so I had been using a custom Neo class that was using the official tdt python package.

However, I went back to the Neo tdtio and with a few changes in the tdtrawio file I am now able to load my data through neo.

The only issue now is that my 32 channel array is split in two 16 channels streams in the Neo object and therefore I can only load half of the data in a spikeinterface recording object. Is there an easy way to load these two 16 channels streams in one 32 channel stream in spikeinterface or something equivalent to allow me to spike sort everything together?

**Comment by samuelgarcia** [comment]
Hi @JulesLebert.
If parralel is not working we need to find a solution because the need of serielize a recording for parralel processing is a string need every where in spikeinterface.

About your change in neo lets discuss the problem of splited channel on your PR on neo side.

**Comment by JulesLebert** [comment]
I understand, I close this PR and follow up on Neo side then! Thank you

**Pull request closed without merging**
