### PR TITLE
Proposal for comparison with ground truth.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@colehurwitz @alejoe91 : **before** a release of spikeinterface I really want to finish the documantion on  spikecomparison.

We need a clear description of the workflow.
[this](https://spikeforest.flatironinstitute.org/metrics) is a good start but I also want to descibe all steps:
  * matching spike (delta_times)
  * matching units (hugarian, best match...)
  * count score
  * agreement matrix
  * confusion matrix
  * labelling individual spike ...

Everyhting must be cristal clear.
It is not the case at the moment.

I think Ican start working on this wendsnday but I will need some help to repharse my english. :)

I plan to include an example, is it OK to include in the git some NPZ light weiht data ?

**Comment by alejoe91** [comment]
Hi @samuelgarcia 

I suggets to merge this! I'll look into the english later and make another PR (also with some other typos here an there).

Ok?

**Comment by samuelgarcia** [comment]
No.
I am currently working on sorter comparison doc.
I will finish it some hours.
And then we can merge.

**Comment by samuelgarcia** [comment]
@alejoe91 : I propose to merge now and so you can will be able to change sorters_comparison.rst.
I think I must change figures. Tell me.

**Comment by colehurwitz** [comment]
For the changing figures, are you planning to change the figures in the paper?

**Comment by samuelgarcia** [comment]
Hi Cole.
No. This is just some matrix to explain all steps for comparison to GT.
Tell me what you think.
Alesiso will change gramars and typos.
It is drafty at the moment.

**Pull request merged**
