### PR TITLE
Fix neo release bug in Mearec

### PR DESCRIPTION
**Pull request by h-mayorquin**
I just remembered about this. Tests were failing on neuroconv because of this.

This eliminates a bug that should disappear with the next release in neo.

### CODE REVIEW

**Comment by h-mayorquin** [comment]
The documentation failing to build is unrelated to this issue and most likely related to a lack of lower bound for numpy version.

**Review by samuelgarcia — APPROVED** [review]

**Comment by samuelgarcia** [comment]
I think this is wise before the relase neo.

**Comment by alejoe91** [comment]
I agree! @h-mayorquin fixing nunpy<1.25 solves the docs issue?

**Comment by h-mayorquin** [comment]
Not sure, don't have time to test @alejoe91 .

**Review by alejoe91 — APPROVED** [review]

**Pull request merged**
