### PR TITLE
add presence plot

### PR DESCRIPTION
**Pull request by ferchaure**
Hi guys, What do you think about this widget?. We use a similar plot to find overclustering due drifting and I thought that could be useful. For long recordings or with units with noisy detections this way to plot activity makes more sense that the raster

### CODE REVIEW

**Comment by alejoe91** [comment]
Looks good @ferchaure 

Just pushed some minor changes: added the function/class to the `__init__`, formatted code, and fixed a matplotlip warning. Good to go from my side. Thanks!

**Review by alejoe91 — APPROVED** [review]

**Comment by samuelgarcia** [comment]
Cool. Thank you. Maybe we could add this in the example galery, no ?

**Comment by ferchaure** [comment]
It looks good, do you need something more to merge?

**Comment by alejoe91** [comment]
Nope ;) thanks for pinging!

**Pull request merged**
