### PR TITLE
Fix the sample_shifts for spikeglx when not all channel are saved.

### PR DESCRIPTION
**Pull request by samuelgarcia**
@alejoe91 
@yger 

This depend on https://github.com/SpikeInterface/probeinterface/pull/151.
Pierre can you test it ?

### CODE REVIEW

**Comment by yger** [comment]
Thanks a lot ! With the two small fixes that I've made (in probeinterface and your PR in spikeinterface, this is working)

**Comment by yger** [comment]
comments

**Comment by samuelgarcia** [comment]
@alejoe91 : ready to merge.

**Review by yger — APPROVED** [review]

**Comment by yger** [comment]
@alejoe91 Can I merge this one? It has been tested

**Pull request merged**
