### PR TITLE
Add core test on all OS with github actions

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 : I have add this to try the core on all OS.
Tell me what you think.

**Comment by samuelgarcia** [comment]
If it is too slow lets remove it

**Comment by samuelgarcia** [comment]
@alejoe91 : bug fixed. merge this soon to finish the doc.

**Review by alejoe91 — APPROVED** [review]

**Comment by samuelgarcia** [comment]
cool

**Pull request merged**
