### PR TITLE
Create suppress_artifacts.py

### PR DESCRIPTION
**Pull request by timsainb**
This is a simple preprocessor that I've been using on my data. It looks for unreasonably high amplitude events, and removes them, filling with either zeros, or noise matched to the data. Sometimes, with very long chronic recordings, the tether can get a bit loose, and there will be noise artifacts or motion artifacts in the data that mess with different sorting algorithms. I've been using it in my chronic recordings and it helps in salvaging recordings that have small sections of corrupted data.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Tim,
thankds for this. I will have a look.
Did you check the already existing toolkit/preprocessing/remove_artifacts.py ?
Maybe if there are some common part we could make one class with several submethods, no ?

**Comment by samuelgarcia** [comment]
The file you proposed is the old API.
The new spikeinetrface have multi segment.
This will be imcompatible. Have a look to other processing stuuf, the get_tarce is delegated to RecordingSegment now.

**Comment by samuelgarcia** [comment]
Any news here ?

**Comment by timsainb** [comment]
I rewrote the preprocessor for the new API, but haven't tried to integrate it with your other artifact removal API. I could still make a PR if you'd like, and you could decide if it's worth trying to merge the two.

**Comment by alejoe91** [comment]
Hi @timsainb 

We'll close this one for now but we look forward to a new API with the new version of noisereduce :)

Cheers
Alessio

**Pull request closed without merging**
