### PR TITLE
Build extractor dicts automatically

### LINKED ISSUE #3168: `get_neo_stream` broken after removing extractor class `name` attributes

### PR DESCRIPTION
**Pull request by alejoe91**
Fixes #3168

### CODE REVIEW

**Review by zm711 — COMMENTED** [review]
Should there be a test for this then just to make sure the machinery of `get_neo_streams` doesn't break again?

**Review by h-mayorquin — APPROVED** [review]
LGTM

What do you think of deprecating this function in another PR?

The same behavior can be achieved by using the class method `get_streams` and that seems better because the user does not need to know in advance the string that corresponds to the extractor (e.g. does not need to know to know that `spikeglx` corresponds to `read_spikeglx`). Plus, because we have the class we can have better error messages and import the io reader directly without having to build an ad-hoc dictionary as we do here.

**Comment by h-mayorquin** [comment]
We would just need to change the docs and throw a deprecation here.

**Comment by alejoe91** [comment]
I think that the `get_neo_streams` is super useful and I use it all the time :)

**Comment by alejoe91** [comment]
> Should there be a test for this then just to make sure the machinery of `get_neo_streams` doesn't break again?

Let's merge for now and open an issue about adding this test

**Pull request merged**
