### PR TITLE
Get default encoding for Popen

### LINKED ISSUE #3429: The following coding errors will occur when the Chinese system is used
When running the following code, if the Chinese system is used, the following error will be reported
image
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[3], [line 2](vscode-notebook-cell:?execution_count=3&line=2)
      [1](vscode-notebook-cell:?execution_count=3&line=1) print("Available sorters", ss.available_sorters())
----> [2](vscode-notebook-cell:?execution_count=3&line=2) print("Installed sorters", ss.installed_sorters())

File e:\anaconda\envs\spike\lib\site-packages\spikeinterface\sorters\sorterlist.py:65, in installed_sorters()
     [62](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/sorterlist.py:62) def installed_sorters():
     [63](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/sorterlist.py:63)     """Lists installed sorters."""
---> [65](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/sorterlist.py:65)     return sorted([s.sorter_name for s in sorter_full_list if s.is_installed()])

File e:\anaconda\envs\spike\lib\site-packages\spikeinterface\sorters\sorterlist.py:65, in <listcomp>(.0)
     [62](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/sorterlist.py:62) def installed_sorters():
     [63](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/sorterlist.py:63)     """Lists installed sorters."""
---> [65](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/sorterlist.py:65)     return sorted([s.sorter_name for s in sorter_full_list if s.is_installed()])

File e:\anaconda\envs\spike\lib\site-packages\spikeinterface\sorters\external\hdsort.py:92, in HDSortSorter.is_installed(cls)
     [90](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/external/hdsort.py:90) @classmethod
     [91](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/external/hdsort.py:91) def is_installed(cls):
---> [92](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/external/hdsort.py:92)     if cls.check_compiled():
     [93](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/external/hdsort.py:93)         return True
     [94](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/external/hdsort.py:94)     return check_if_installed(cls.hdsort_path)

File e:\anaconda\envs\spike\lib\site-packages\spikeinterface\sorters\basesorter.py:375, in BaseSorter.check_compiled(cls)
    [367](file:///E:/anaconda/envs/spike/lib/site-packages/spikeinterface/sorters/basesorter.py:367) shell_cmd = f"""
...
--> [322](file:///E:/anaconda/envs/spike/lib/codecs.py:322)     (result, consumed) = self._buffer_decode(data, self.errors, final)
    [323](file:///E:/anaconda/envs/spike/lib/codecs.py:323)     # keep undecoded input until the next call
    [324](file:///E:/anaconda/envs/spike/lib/codecs.py:324)     self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 5: invalid start byte
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?b2045021-aa99-4016-a457-2771d172b69d) or open in a [text editor](command:workbench.action.openLargeOutput?b2045021-aa99-4016-a457-2771d172b69d). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**I solved this problem by adding the following code to shellscript.py. Is there a better solution?**
add `encoding='gbk'` when using subprocess.Popen
image

### PR DESCRIPTION
**Pull request by alejoe91**
Should fix #3429

### CODE REVIEW

**Review by zm711 — APPROVED** [review]
That's super cool. I don't know if you want one of the issue folks to test it. Testing on my computer worked, but mine is `utf-8` anyway.

**Comment by alejoe91** [comment]
Yeah! 
@522848942 and @jonpedros could you test this PR? Do you know how to install from source?

**Comment by zm711** [comment]
Hey @522848942 and @jonpedros, just wanted to see if you'd be willing to test this for us to see if this fixes your issues with encoding?

**Comment by jonpedros** [comment]
> Hey @522848942 and @jonpedros, just wanted to see if you'd be willing to test this for us to see if this fixes your issues with encoding?

Will test this today!

**Comment by jonpedros** [comment]
> Hey @522848942 and @jonpedros, just wanted to see if you'd be willing to test this for us to see if this fixes your issues with encoding?

Testing in my Japanese locale PC worked!

**Pull request merged**
