### PR TITLE
Implementing read_spikeglx_event()

### PR DESCRIPTION
**Pull request by manimoh**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi.
Thanks for this.
This PR is a bit strange because at the momement spikeglx do not handle event in neo.
See this line https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/spikeglxrawio.py#L178

Do you plan to handle events on neo side ?
DO you know how spikeglx handle events ?

**Comment by manimoh** [comment]
Hi @samuelgarcia 
Sorry for the late reply!
I did start a [PR](https://github.com/NeuralEnsemble/python-neo/pull/1383) on the neo repo to implement handling of events. So once that is merged, I guess this can be merged too?

**Comment by zm711** [comment]
Fixes #2242.

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
Yes! Sorry for the delay on this @TheChymera

**Pull request merged**
