### PR TITLE
Fast templates: compute `std` with and extend to widgets

### PR DESCRIPTION
**Pull request by alejoe91**
With the same approach of computing the template means with an accumulator, this PR adds the computation of std "online".

The idea is the following:

$$
template_{std}  = \sqrt{\frac{\sum_i (w_i - \mu)^2}{N}} = \sqrt{\frac{\sum_i w_i^2 + N \cdot \mu - 2 \cdot \mu \cdot \sum_i w_i}{N}}
$$

Since the `estimate_template_average` (now renamed `extimate_template_online` -- another possible name is `estimate_template_one_pass`/`from_traces`) already accumulates the waveforms $\sum_i w_i$, we just need to extent the mechanism to $\sum_i w_i^2$ and the trick is quickly done.

Added a test to assess it gives the same result as `ComputeTemplates` ;)

### CODE REVIEW

**Comment by alejoe91** [comment]
@yger now plots are compatible with `fast_templates`. Wanna try it out?

**Comment by yger** [comment]
Oh yeah, thanks a lot @alejoe91, I'll do that asap!

**Comment by DradeAW** [comment]
@alejoe91 This PR makes lussac crash:

```
    def test_compute_graph(data: LussacData) -> None:
    	sortings = {
    		'1': si.NumpySorting.from_unit_dict({0: np.array([100, 300]), 1: np.array([350, 500]), 2: np.array([200, 400, 600])}, sampling_frequency=30000),
    		'2': si.NumpySorting.from_unit_dict({0: np.array([150, 400]), 1: np.array([650, 800]), 2: np.array([150, 750, 900])}, sampling_frequency=30000),
    		'3': si.NumpySorting.from_unit_dict({0: np.array([500, 900]), 1: np.array([400, 700])}, sampling_frequency=30000)
    	}
    	multi_sortings_data = MultiSortingsData(data, sortings)
    	module = MergeSortings("merge_sortings_graph", multi_sortings_data, "all")
    
    	similarity_matrices = {
    		'1': {
    			'2': np.array([[0.9, -0.05, 0.2], [0.02, 0.95, 0.6], [-0.03, 0.0, 0.01]]),
    			'3': np.array([[1.0, 0.03], [0.0, -0.6], [0.0, 0.0]])
    		},
    		'2': {
    			'1': np.array([[0.9, 0.02, -0.03], [-0.05, 0.95, 0.0], [0.2, 0.6, 0.01]]),
    			'3': np.array([[0.95, -0.01], [0.04, -0.04], [0.4, 0.3]])
    		},
    		'3': {
    			'1': np.array([[1.0, 0.0, 0.0], [0.03, -0.6, 0.0]]),
    			'2': np.array([[0.95, 0.04, 0.4], [-0.01, -0.04, 0.3]])
    		}
    	}
    
    	p = {
    		'refractory_period': (0.2, 1.0),
    		'similarity': {'min_similarity': 0.4},
    		'require_multiple_sortings_match': False,
    		'waveform_validation': {'wvf_extraction': {'filter': None}}
    	}
    	p = module.update_params(p)
    
>   	module._create_analyzer(p['waveform_validation']['wvf_extraction'])

tests/modules/test_merge_sortings.py:112: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/lussac/modules/merge_sortings.py:100: in _create_analyzer
    self.analyzer.compute({
../../dev/spikeinterface/spikeinterface/src/spikeinterface/core/sortinganalyzer.py:774: in compute
    self.compute_several_extensions(extensions=input, save=save, **job_kwargs)
../../dev/spikeinterface/spikeinterface/src/spikeinterface/core/sortinganalyzer.py:893: in compute_several_extensions
    self.compute_one_extension(extension_name, save=save, **extension_params)
../../dev/spikeinterface/spikeinterface/src/spikeinterface/core/sortinganalyzer.py:843: in compute_one_extension
    extension_instance.run(save=save, **job_kwargs)
../../dev/spikeinterface/spikeinterface/src/spikeinterface/core/sortinganalyzer.py:1438: in run
    self._run(**kwargs)
../../dev/spikeinterface/spikeinterface/src/spikeinterface/core/analyzer_extension_core.py:534: in _run
    self.data["average"], self.data["std"] = estimate_templates_with_accumulator(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

recording = BinaryFolderRecording: 26 channels - 30.0kHz - 1 segments - 27,000,000 samples 
                       900.00s (15.00 minutes) - int16 dtype - 1.31 GiB
spikes = array([(100, 0, 0), (150, 3, 0), (150, 5, 0), (200, 2, 0), (300, 0, 0),
       (350, 1, 0), (400, 3, 0), (400, 2, 0), ... 0), (900, 6, 0), (900, 5, 0)],
      dtype=[('sample_index', '<i8'), ('unit_index', '<i8'), ('segment_index', '<i8')])
unit_ids = array([0, 1, 2, 3, 4, 5, 6, 7]), nbefore = 69, nafter = 99, return_scaled = True, job_name = 'estimate_templates_with_accumulator'
return_std = True, job_kwargs = {'chunk_duration': '2s', 'max_threads_per_process': 1, 'mp_context': None, 'n_jobs': 2, ...}, num_worker = 2
num_chans = 26, num_units = 8, shape = (2, 8, 168, 26), dtype = dtype('float32')
waveform_accumulator_per_worker = array([[[[ 1117.35   ,  -546.975  , -5943.21   , ...,  1577.7449 ,
           1080.69   ,   898.17   ],
         [ 110...       [    0.     ,     0.     ,     0.     , ...,     0.     ,
              0.     ,     0.     ]]]], dtype=float32)
shm = SharedMemory('psm_4375577e', size=279552)

    def estimate_templates_with_accumulator(
        recording: BaseRecording,
        spikes: np.ndarray,
        unit_ids: list | np.ndarray,
        nbefore: int,
        nafter: int,
        return_scaled: bool = True,
        job_name=None,
        return_std: bool = False,
        **job_kwargs,
    ):
        """
        This is a fast implementation to compute template averages and standard deviations.
        This is useful to estimate sparsity without the need to allocate large waveform buffers.
        The mechanism is pretty simple: it accumulates and sums spike waveforms (and their squared)
        in-place per worker and per unit.
        Note that median and percentiles can't be computed with this method, because they don't support
        the accumulator implementation.
    
        Parameters
        ----------
        recording: BaseRecording
            The recording object
        spikes: 1d numpy array with several fields
            Spikes handled as a unique vector.
            This vector can be obtained with: `spikes = sorting.to_spike_vector()`
        unit_ids: list ot numpy
            List of unit_ids
        nbefore: int
            Number of samples to cut out before a spike
        nafter: int
            Number of samples to cut out after a spike
        return_scaled: bool, default: True
            If True, the traces are scaled before averaging
        return_std: bool, default: False
            If True, the standard deviation is also computed.
    
        Returns
        -------
        templates_array: np.array
            The average templates with shape (num_units, nbefore + nafter, num_channels)
        """
    
        assert spikes.size > 0, "estimate_templates() need non empty sorting"
    
        job_kwargs = fix_job_kwargs(job_kwargs)
        num_worker = job_kwargs["n_jobs"]
    
        num_chans = recording.get_num_channels()
        num_units = len(unit_ids)
    
        shape = (num_worker, num_units, nbefore + nafter, num_chans)
        dtype = np.dtype("float32")
        waveform_accumulator_per_worker, shm = make_shared_array(shape, dtype)
        shm_name = shm.name
        if return_std:
            waveform_squared_accumulator_per_worker, shm_squared = make_shared_array(shape, dtype)
            shm_squared_name = shm_squared.name
        else:
            waveform_squared_accumulator_per_worker = None
            shm_squared_name = None
    
        # trick to get the work_index given pid arrays
        lock = multiprocessing.Lock()
        array_pid = multiprocessing.Array("i", num_worker)
        for i in range(num_worker):
            array_pid[i] = -1
    
        func = _worker_estimate_templates
        init_func = _init_worker_estimate_templates
    
        init_args = (
            recording,
            spikes,
            shm_name,
            shm_squared_name,
            shape,
            dtype,
            nbefore,
            nafter,
            return_scaled,
            lock,
            array_pid,
        )
    
        if job_name is None:
            job_name = "estimate_templates_with_accumulator"
        processor = ChunkRecordingExecutor(recording, func, init_func, init_args, job_name=job_name, **job_kwargs)
        processor.run()
    
        # average
        waveforms_sum = np.sum(waveform_accumulator_per_worker, axis=0)
        template_means = waveforms_sum
        unit_indices, spike_count = np.unique(spikes["unit_index"], return_counts=True)
        template_means[unit_indices, :, :] /= spike_count[:, np.newaxis, np.newaxis]
    
        if return_std:
            waveforms_squared_sum = np.sum(waveform_squared_accumulator_per_worker, axis=0)
            # standard deviation
            template_stds = np.zeros_like(template_means)
            for i, (unit_index, count) in enumerate(zip(unit_indices, spike_count)):
                residuals = (
                    waveforms_squared_sum[unit_index] - 2 * count * template_means[unit_index] * waveforms_sum[unit_index]
                ) + count * template_means[unit_index] ** 2
                template_stds[unit_index] = np.sqrt(residuals / count)
>           assert np.all(template_stds >= 0)
E           AssertionError

../../dev/spikeinterface/spikeinterface/src/spikeinterface/core/waveform_tools.py:880: AssertionError
```

Apparently some stds are negative ...

Also, could it be possible to give the option of computing only average, or both?

**Comment by alejoe91** [comment]
@DradeAW oups! We should track this down. I added a test to make sure that "fast" stds are similar to almost equal to real stds..so that's strange

**Pull request merged**
