### PR TITLE
Add original_cluster_id to PhySortingExtractor

### PR DESCRIPTION
**Pull request by DradeAW**

### CODE REVIEW

**Comment by DradeAW** [comment]
> In our testing files that we have the cluster_id is identical to the indexes you are using. Are they different in your files?

After `sorting = PhySortingExtractor("path/to/phy")`, for some of them the unit ids are not the same as the cluster_id in phy.
This is why I wanted to track the original cluster_id.

@alejoe91 You're right!
I'll make the fix right away :)

**Comment by h-mayorquin** [comment]
> After sorting = PhySortingExtractor("path/to/phy"), for some of them the unit ids are not the same as the cluster_id in phy.
This is why I wanted to track the original cluster_id.

@alejoe91 @DradeAW  I don't understand why would they be different if we have the following line which sets the `units_ids` to the `cluster_id` from the files?

https://github.com/SpikeInterface/spikeinterface/blob/48aa2285a719461586d38e0210c5d2c0e06cee12/src/spikeinterface/extractors/phykilosortextractors.py#L136

**Comment by DradeAW** [comment]
> I don't understand why would they be different if we have the following line which sets the units_ids to the cluster_id from the files?

Good question, let me investigate :)

**Comment by DradeAW** [comment]
Ah it's simply because I have a file `cluster_si_unit_ids.tsv`
But I'd still like to know the original cluster_id in phy.

**Comment by alejoe91** [comment]
Because if you save with SI we add a custom column (`si_unit_id`) to make sure that when we load it back the same SI unit IDs are preserved. See the other part of the if-else statement

**Comment by h-mayorquin** [comment]
> Because if you save with SI we add a custom column (`si_unit_id`) to make sure that when we load it back the same SI unit IDs are preserved. See the other part of the if-else statement

@alejoe91 Thanks. That makes sense.

**Review by alejoe91 — APPROVED** [review]

**Pull request merged**
