### PR TITLE
Fix reading of legacy OpenEphys recording format

### PR DESCRIPTION
**Pull request by ToGauvrit**
Previously in the version 0.90, only new binary openephys format could be loaded. The legacy format were detected as new one. The problem came from this if condition.

### CODE REVIEW

**Comment by ToGauvrit** [comment]
Fixes this issue : #266

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
Thanks @ToGauvrit :)

**Comment by samuelgarcia** [comment]
THanks and sorry for the bug. It was me obviously.

**Comment by ToGauvrit** [comment]
No problem @samuelgarcia @alejoe91 !  See you maybe in Lyon for the mini-school ;)

**Comment by samuelgarcia** [comment]
Yes. Cool.

**Pull request merged**
