### PR TITLE
Start doc refactoring.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 : this is the new skeleton for documentation

**Review by alejoe91 — APPROVED** [review]

**Comment by samuelgarcia** [comment]
@alejoe91 : I made stronger test for save() after channel slice.
They are passing on linux with python3.8.
Could you checj that tests are passing on your side.

**Comment by samuelgarcia** [comment]
@alejoe91 : even on GH actrions it pass tests.
Can you merge this ? and run tests locally ?

**Comment by samuelgarcia** [comment]
Tests are passing, I merge this.
@alejoe91 : please tests the new master

**Pull request merged**
