### PR TITLE
updated docs to reflect new quality metrics

### PR DESCRIPTION
**Pull request by colehurwitz**
Changed code examples for validation and curation.

### CODE REVIEW

**Comment by colehurwitz** [comment]
Do I need to make an new pip release of spiketoolkit for this to work @samuelgarcia @alejoe91 ?

**Comment by alejoe91** [comment]
If you are relying on new code yes!

**Comment by colehurwitz** [comment]
Can I release a new version of spiketoolkit then?

**Comment by samuelgarcia** [comment]
Hi Cole.
You can make a new version of toolkit when you want if it help to pass travis test.
We will make another one after Alessio change.
I think we can have a fast release cycle for each package and a slow one for the metapackage.

**Comment by colehurwitz** [comment]
@alejoe91 I think this will work with the newest versions of each package.

**Comment by colehurwitz** [comment]
We should probably release new versions of everything. Do you know how many have been released so far? @alejoe91

**Comment by alejoe91** [comment]
I think we should release everything (I noticed you left some print statements in `spikewidgets`!!!)

Then we can test out the tutorial, make sure that it runs smoothly, and merge

**Pull request merged**
