### PR TITLE
new waveclus sorter using h5py

### PR DESCRIPTION
**Pull request by ferchaure**
Hi guys, I forgot to upload this.  I used a feature of wave_clus to allow it to read h5 files. 
Now this code is free of the savemat size limitation.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Fernando,
this is good for me.
be aware that doing this all units even bad one will be integrated in all benchmark with this patch.
Maybe you could add a option load_unsorted=False/True like they do in kilosort.

**Comment by ferchaure** [comment]
Ok I will take a look, and probably included on the combinato sorter as well.

**Comment by ferchaure** [comment]
done, what about the others sorters? artifacts and unsorted should be removed using this parameter?

**Comment by alejoe91** [comment]
@ferchaure this is already implemented for the Kilosorts and HDsort, that have this option! Thanks for the updates. Looks good to me :)

One comment that we could address in the future. I noticed you write the entire trace of a channel in one shot. If a recording is very long this could fill up all memory. I think we should add some chunking there!

**Comment by ferchaure** [comment]
added the chunking  @alejoe91  (I have everything there I just forgot to implement it).

**Comment by alejoe91** [comment]
> added the chunking @alejoe91 (I have everything there I just forgot to implement it).

Great! Can you expose the `chunk_memory` arg as an additional parameter and propagate it to the `write_to_h5_dataset_format`? https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/core_tools.py#L354-L355

**Comment by ferchaure** [comment]
Done. The documentation on write_to_h5_dataset_format  about chunk_size and chunk_memory is a bit confusing. It says _chunk_mb_ but maybe is talking about _chunk_memory_, and chunk_memory could be a string

**Comment by alejoe91** [comment]
It's still from the old documentation. We have to carefully update the docstrings for all functions. Would you mind updating the write_h5 one? Sorry for all these requests!

**Comment by ferchaure** [comment]
Done, The calculations are in megabytes, then I changed Mb to MB

**Comment by alejoe91** [comment]
Perfect! Thanks :)

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
@samuelgarcia can we merge this?

**Comment by samuelgarcia** [comment]
Hola Fernando.
Perfect.
I merge.
Thanks

**Pull request merged**
