### PR TITLE
Add basic repr to `Templates` object

### PR DESCRIPTION
**Pull request by h-mayorquin**
As in the title. See here for how it looks. Feel free to make recommendations on how this should be. 

image

### CODE REVIEW

**Comment by zm711** [comment]
Seems like the latests test failures might be related to [this GIN PR](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/125). My PR #2717 also has this failure. Not quite sure how datalad works so not sure what is happening with this particular failure.

**Comment by alejoe91** [comment]
> Seems like the latests test failures might be related to [this GIN PR](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/125). My PR #2717 also has this failure. Not quite sure how datalad works so not sure what is happening with this particular failure.

Shoot my bad! I probably merged it too quickly!

**Comment by alejoe91** [comment]
@zm711 yep my bad... I asked for another PR to fix it: https://github.com/NeuralEnsemble/python-neo/pull/1383#issuecomment-2053671762

**Comment by zm711** [comment]
What was the issue? Just so I can know to look in the future. I tried to look at the error, but I don't understand it...

**Comment by alejoe91** [comment]
> What was the issue? Just so I can know to look in the future. I tried to look at the error, but I don't understand it...

I made a new PR where I started from scratch: https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/126

**Comment by alejoe91** [comment]
Ok extractors tests are fixed :)

**Review by alejoe91 — APPROVED** [review]

**Pull request merged**
