### PR TITLE
Improve Documentation VI

### PR DESCRIPTION
**Pull request by zm711**
I noticed a few typos in some of the assert errors, exceptions, doc-strings, so I thought I would work on those a bit. Similar to with the pure docs I'm trying to go through smaller folders first.

### CODE REVIEW

**Comment by h-mayorquin** [comment]
Hi, thanks for the PR.  

This Friday 2023-04-07 we will be changing the default branch from master to main. So new PRs from now on should be branched from main instead of master. Moreover, the new branch main has a [ src package structure](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/) so any changes in code should start from it.

Meanwhile, when you open a PR you can chose the base here (after clicking edit):
image

If you have some extra time could you do this PR from and to main instead?
Otherwise, we merge to master from here and we take care of synching later. That said, if you do other PR this week please do it from main.

**Comment by zm711** [comment]
No worries. I'll close this and switch over to main instead. I'll just make a new pull request sometime this weekend with the changes to minimize stuff on your end.

**Comment by h-mayorquin** [comment]
Thanks a lot! We really appreciate doing this work, if you by any chance don't have time I can do it from what you have done here. Just let us know!

**Comment by zm711** [comment]
It's all good.  Happy to help (and rereading the functions gives me a better internal sense of what's going on which is helpful in and of itself). And I really appreciate the switch to main--thanks for doing that!

**Pull request closed without merging**
