### PR TITLE
Protect median against nans in get_prototype_spike

### PR DESCRIPTION
**Pull request by alejoe91**
as in title! nan median is needed in case some waveforms are flat!

### CODE REVIEW

**Review by h-mayorquin — COMMENTED** [review]
I have always wondering if there is a performance penalty for using these safe functions.

**Comment by alejoe91** [comment]
@h-mayorquin seems very minor, and it solves the issue!

**Comment by alejoe91** [comment]
Nothing seems wrong with the data honestly. Maybe the fix is not working as it should? Do we have a proper test? Note that I was not getting any failure, just all estimated spike locations were 0

**Review by yger — APPROVED** [review]

**Comment by yger** [comment]
No proper tests of course, but I'll have a look. Meanwhile, the fix can not hurt and indeed. However before the fix, at least there was messages with numpywarning during the estimation of the prototype if nan/0 were found. In your case, before the fix, you saw such messages before getting your 0 positions?

**Comment by alejoe91** [comment]
Nope, because it's protected by the `with np.errstate(divide="ignore", invalid="ignore"):` ...

**Comment by h-mayorquin** [comment]
> @h-mayorquin seems very minor, and it solves the issue!

Yeah, sorry, I was not trying to argue against just wondering for myself. I agree that performant code that is buggy is worse than ultra-slow-code that is sound. I was just taking the opportunity to see if you guys knew. I feel that is good to be aware of these things.

A reading of the source indicates that it doubles (or triples?) the memory cost:
https://github.com/numpy/numpy/blob/v2.0.0/numpy/lib/_nanfunctions_impl.py#L968-L1071

The strategy for both nanmean and mean seem to sum and count so I expect the most costly loop to be the same.

**Pull request merged**
