### PR TITLE
[MNT] - Doc updates & lints for sorting components

### PR DESCRIPTION
**Pull request by TomDonoghue**
This is a sweep through of the sorting_components sub-module, doing some doc updates / clean ups, and minor code linting.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Tom.
Thanks a again for this big clean. I am sorry to leave some drafty docstring.
I guess I can merge this.

**Review by samuelgarcia — APPROVED** [review]

**Comment by samuelgarcia** [comment]
Oups, there is an error in tests could you check ?

**Comment by samuelgarcia** [comment]
You should avoid `{...}` in docs because we sometimes format it to extend some kwargs (job_kwargs).

**Comment by samuelgarcia** [comment]
@TomDonoghue : could you remove the `{}` in the docstring, they are breaking some formating.

**Comment by alejoe91** [comment]
Fixed here: https://github.com/SpikeInterface/spikeinterface/pull/390

**Comment by TomDonoghue** [comment]
Hey @samuelgarcia - sorry for not following up on this earlier, I've been travelling and didn't get a chance to get back to this! Thanks to @alejoe91 for picking this up and getting it merged!

**Pull request merged**
