### PR TITLE
Add censorship of correlograms in `scur.auto_merge`

### PR DESCRIPTION
**Pull request by DradeAW**
Some sorters can detect spikes multiple times.
This results in peaks in the auto and/or cross-correlograms that can impact detection of merged units.
This should fix it.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@DradeAW : I understand the goal but this also artificialy break the main idea of the correlogram no ?
for duplicated spikes it would be better to be explicit.

I would not put censor_correlograms_ms=1.5 by default.
Are you targeting a few sample for duplicated  spikes  ?

**Comment by DradeAW** [comment]
> I would not put censor_correlograms_ms=1.5 by default
I put 0.15 by default! (it can be reduced to 0.10)

> I understand the goal but this also artificialy break the main idea of the correlogram no ?
I don't think it really break the idea because there is a gaussian filtering afterwards that takes into consideration a much bigger window that the censorship window.
Now I'm not against putting a value of 0.0 by default if you think it's best :)

**Comment by samuelgarcia** [comment]
>I put 0.15 by default! (it can be reduced to 0.10)
oups sorry I read it to quicly.
make more sens
Lets keep this default
I still think that we should clean duplicated spikes before this.

**Comment by DradeAW** [comment]
Cleaning duplicated spikes will work for auto-correlograms, but not for cross-correlograms!

Some sorters can detect the same spike multiple time and assign it in different units.

**Review by samuelgarcia — APPROVED** [review]

**Pull request merged**
