### PR TITLE
Remove warning

### PR DESCRIPTION
**Pull request by DradeAW**
BinaryRecordingExtractor with `num_chan`

### CODE REVIEW

**Review by alejoe91 — APPROVED** [review]

**Comment by h-mayorquin** [comment]
Thanks for looking at the warnings!

**Comment by h-mayorquin** [comment]
Sorry, closed it accidentally while commenting!

**Review by samuelgarcia — APPROVED** [review]

**Comment by DradeAW** [comment]
The latest version of hdbscan (0.8.33) solves the issue.
You don't need to specify any version of Cython, hdbscan will take care of it as of version 0.8.33 (it now specifies Cython<3)

**Comment by h-mayorquin** [comment]
@DradeAW 
That's great, just released yesterday, right?

**Comment by DradeAW** [comment]
> That's great, just released yesterday, right?

Yep, yesterday around 8:00pm (Paris time)

**Comment by h-mayorquin** [comment]
OK, let's see:
https://github.com/SpikeInterface/spikeinterface/pull/1849

**Comment by alejoe91** [comment]
So installation works, but `find_cluster_from_peaks` is probably propagating some deprecated kwargs..

**Pull request merged**
