### PR TITLE
(WIP) sphinx-gallery documentation

### PR DESCRIPTION
**Pull request by alejoe91**
@samuelgarcia merged your PR and created a new one from a branch so we have write access.

In the other case, everytime we pushed to your PR a new branch would have been created.

I reorganized the docs a bit:

- overview
- getting started
- modules --------- extractors, toolkit, sorters, comparison, widget examples
- usage ----------- gallery of examples (Neuropixels, MEArec, advanced usage)

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Alessio.
Thank for the merge and the work in progress on this.

We still have a problem of import of spikeextractors flat or not flat.
See https://github.com/SpikeInterface/spikeextractors/pull/236

We also, we decide very soon what is the official the doc do thing:

  1. si.extractors.XXXX
  2. se.XXXX
  (3. si.XXXX) not accepted the fla one
   
I know, that you like the 2. Maybe the 2. would be better.
I have started  the doc with 2 because it simplify the import problem for the moement.

**Comment by samuelgarcia** [comment]
I think the overview should be something more general instead of explaining that it is a metapackage.
I think nobody should care about the metapackage unless devs.

This overvieew should be more like the abstract of the paper.

No ?

**Comment by samuelgarcia** [comment]
I also think that widget examples should be split into many many small files because here the gallery make sens and we should need many small icon generated by many scripts.

No ?

**Comment by alejoe91** [comment]
> Hi Alessio.
> Thank for the merge and the work in progress on this.
> 
> We still have a problem of import of spikeextractors flat or not flat.
> See [SpikeInterface/spikeextractors#236](https://github.com/SpikeInterface/spikeextractors/pull/236)
> 
> We also, we decide very soon what is the official the doc do thing:
> 
> 1. si.extractors.XXXX
> 2. se.XXXX
>    (3. si.XXXX) not accepted the fla one
> 
> I know, that you like the 2.
> Maybe the 1 would be better.
> I have started the doc with 2 because it simplify the import problem for the moement.

Hi Sam,

I vote for option 2. I think the API looks more compact. For now let's comment out the flat one until we fix it.

Overview: I agree. We can start with something like the abstract. But I would also introduce the packages and scope and the spikeinterface package (maybe without calling it a meta-package). Ok?

Widgets. Sure! I can split: Widgets for RecordingExtractors, SortingExctractors, Rec+Sort, Comparison

**Comment by alejoe91** [comment]
ok merging this then

**Pull request merged**
