### PR TITLE
Remove `from __future__ import annotations` after dropping 3.8

### PR DESCRIPTION
**Pull request by alejoe91**

### CODE REVIEW

**Comment by zm711** [comment]
We have some 3.10 + only... the | is 3.10 :(

**Comment by alejoe91** [comment]
My bad!

**Comment by zm711** [comment]
No worries. Valiant effort. I think after 3.10 all the typing stuff has calmed down so it should be easy :)

**Comment by h-mayorquin** [comment]
Numpy is already at minimal 3.10 https://numpy.org/neps/nep-0029-deprecation_policy.html x D

**Pull request closed without merging**
