### PR TITLE
Poetry support

### PR DESCRIPTION
**Pull request by caniko**
[Poetry](https://python-poetry.org/) is in my humble opinion the next iteration of the `setup.py` paradigm for defining, and uploading python packages to PyPi.

**Motivation**
I had trouble installing all the optional dependencies alongside each other for proper testing during the development of my other PR (#477). Implementing poetry support seemed easier than hacking my way through the problem.

**Notable changes**
- `poetry.lock` stores versions of the entire dependency tree, ensuring package stability in the future.
- Version and other package metadata is stored in `pyproject.toml`. Removed `setup.py` and requirement files as they are redundant.
- Support for both Python 3.8 and 3.9

**TODO before testing on CD**
- [x] Update files on `.github/workflows`
- [ ] Migrate project to `pyproject.toml`

### CODE REVIEW

**Comment by caniko** [comment]
I can look into getting support for Python 3.8 back. I think it might be related to `pandas`, we will have to use an older version on Python 3.8. What do you think @alejoe91? Is it worth it, or should we just upgrade the minimum requirements to 3.9?

**Comment by alejoe91** [comment]
Hi @caniko 

Thanks for it! Let's have a call to discuss about what we should and what we should not put as installation options.

I'll send you an email ;)

**Comment by caniko** [comment]
@samuelgarcia here is an [article](https://remastr.com/blog/pip-pipenv-poetry-comparison) discussing the current landscape of python dependency management tools.

I might be biased linking to this article because it is pro-poetry like myself, but there really is nothing that comes even close to `poetry` (imho).

**Comment by samuelgarcia** [comment]
Hi Can,
thank you for the link, it is same I selected randomly yesertday for my reading. I am progressing!

**Comment by caniko** [comment]
I [packaged](https://github.com/caniko/spikeinterface_poetry) `spikeinterface` in a secondary PyPi repository downstream from this one.

We are using this in our lab for now. Maybe you can give it a try!?

**Comment by alejoe91** [comment]
@caniko as we agreed let's keep poetry support for future releases. At this point I think it's easier to close this PR and start from scratch after the next release. Thank you for opening our eyes on these new setup options!

**Pull request closed without merging**
