### PR TITLE
Fix 'single' common referencing

### PR DESCRIPTION
**Pull request by khl02007**
@alejoe91

Common referencing with `reference=single` behaves incorrectly because the reference channel ID is not first converted to index prior to subtraction. This PR tries to fix it. Let me know if this is the correct use of `self.ids_to_indices`.

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Good catch.
I never use this mode and did not port it correctly to new API.
thanks a lot.
Could you also fix line 73 `assert ref_channels.dtype.kind == 'i', "'ref_channels' must be int"` which is also wrong.

I would also vote for a variable renaming to avoid problem `ref_channels` to `ref_channel_ids`.
@alejoe91 @khl02007 : what do you think ?

**Comment by samuelgarcia** [comment]
@khl02007 could you also add a small test for this ?

**Comment by alejoe91** [comment]
> Good catch. I never use this mode and did not port it correctly to new API. thanks a lot. Could you also fix line 73 `assert ref_channels.dtype.kind == 'i', "'ref_channels' must be int"` which is also wrong.

I would add:
```
assert np.all([ch in self.get_channel_ids() for ch in ref_channel_ids]), "Some wrong 'ref_channel_ids'!"
```


> I would also vote for a variable renaming to avoid problem `ref_channels` to `ref_channel_ids`. @alejoe91 @khl02007 : what do you think ?

Agreed

**Comment by khl02007** [comment]
* renamed variables as suggested: `ref_channel_ids` and `ref_channel_inds` 
* changed line 73 to what @alejoe91 suggested

@samuelgarcia do you mean a test specifically for the index issue? To do so I need a recording whose channel ids are not the same as channel indices. OK to do that to `rec` created with `generate_recording` in `test_common_reference.py`?

**Comment by samuelgarcia** [comment]
@khl02007 : in test_common_reference.py we already tests the `reference='single'`
So normally it is already tested.
Maybe we could add this to be sure that the ids is used
```python
def test_common_reference():
    rec = generate_recording(durations=[5.], num_channels=4)
    rec._main_ids = np.array(['a', 'b', 'c', 'd'])
    rec = rec.save()

   ...
   rec_sin = common_reference(rec, reference='single', ref_channel_ids=['b'])
   ...

```

**Comment by khl02007** [comment]
@samuelgarcia did as you suggested, also locally verified that test passes

**Review by alejoe91 — APPROVED** [review]

**Pull request merged**
