### PR TITLE
Deteccion without duplicated  events

### PR DESCRIPTION
**Pull request by ferchaure**
Hi guys, 
A new method for detection removing duplicated events (I talked about this on #363). I removed the part of the criteria related euclidean distances, because it tricky to interpret it in different preprocessing pipeline and ask by default that 90% of the channels has the same deteccion. It requires that some channels are far away (to easily say that duplicated detections are artifacts) but is really useful for contaminated recordings.

I thought to implement this in a family of functions to clean detections but it will have a better performance here.

### CODE REVIEW

**Comment by ferchaure** [comment]
I guess this doesn't follow the current approach. I will remake this as a cleaning function or similar..

**Comment by alejoe91** [comment]
Hi Fer, sorry I haven't commented on this before, but I have been quite busy in the last weeks. I think that it's nice to add new detection methods/improvements, but maybe it's better to have a proper call with Sam as well to layout what we should add and where. Same goes for your proposal for improving the waveform extractor. What do you think? :)

**Comment by ferchaure** [comment]
Hi Alessio,  I will really like a proper call with you and Sam, let me know when you're available.

This pull request was cool but It was implemented in this way just to make the code faster; the proper way must be inside a function to subselect peaks like the one yger proposed.

**Comment by alejoe91** [comment]
@ferchaure we are closing this one for now. We can discuss at the hackaton on ways to properly integrate it :)

**Pull request closed without merging**
