### PR TITLE
Try to fix hdbscan make failing tests

### PR DESCRIPTION
**Pull request by samuelgarcia**
force numpy 1.20 before neo in actions to avoid hdbscan wring linkage

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@alejoe91 : I think numpy was 1.22 because neo is installed before.
Lets if this make the trick.

**Comment by alejoe91** [comment]
The hdbscan problem is fixed, but there are othe errors. @samuelgarcia can you look into it?

**Comment by samuelgarcia** [comment]
It was because of PR #429 we have merge to early. There was a bug.
I revert it back and will fix it later.

**Comment by samuelgarcia** [comment]
@alejoe91 : this have to be be merge before anyother PR.

**Review by alejoe91 — APPROVED** [review]

**Pull request merged**
