### PR TITLE
Update curation module to use `sorting` argument rather than `parent_sorting`

### PR DESCRIPTION
**Pull request by zm711**

### CODE REVIEW

**Comment by zm711** [comment]
@DradeAW for discussion!

Fix _kwargs

**Comment by zm711** [comment]
After discussion we are good to do the hard break still need to fix the _kwargs.

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
@zm711 ready to review?

**Comment by zm711** [comment]
Oops. I opened all my PRs as drafts because the button was on draft mode. Haha. 

Yeah as long as you're okay with a breaking change this is good to go. Sam and Aurelien said they were okay with it, but the alternative would be to make sorting optional and then do a deprecation instead.

**Comment by alejoe91** [comment]
> Oops. I opened all my PRs as drafts because the button was on draft mode. Haha.
> 
> Yeah as long as you're okay with a breaking change this is good to go. Sam and Aurelien said they were okay with it, but the alternative would be to make sorting optional and then do a deprecation instead.

Let's break! 1.0 here we come :)

**Comment by zm711** [comment]
We have conflicts now. I can work on this on Friday unless you want to just do this before than.

**Comment by alejoe91** [comment]
I can fix it ;)

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
Grazie Zach!

**Comment by samuelgarcia** [comment]
Merci Zach.

**Pull request merged**
