### PR TITLE
Allow `new_unit_id` to be same id in `CurationSorting.merge`

### PR DESCRIPTION
**Pull request by DradeAW**
Right now it's not possible to do `CurationSorting.merge([1, 2], new_unit_id=1)`, and it should be possible

### CODE REVIEW

**Comment by zm711** [comment]
@DradeAW Isn't it a `Phy` convention that the numbers always need to get bigger? So I think if you allow this it would break Phy compatibility if people were going back and forth been SI and Phy.

**Comment by DradeAW** [comment]
But I'm not changing the way it works by default, I'm just giving the user the opportunity to do so if he wishes.

In my code it's important that the unit id stays the same!

**Comment by zm711** [comment]
Totally fair. So the only problem case would be the case where someone wanting to use Phy but not knowing the Phy rules tries to merge to the same number. I don't think there's an easy way to do a warning without bothering users. But if a user just sticks to default it should be fine (so someone not knowing Phy rules would hopefully just use default?) 

I'm understanding that correctly?

**Comment by DradeAW** [comment]
I don't see what the problem is?

You can use `CurationSorting.merge([1, 2], new_unit_id=1)` then `export_to_phy` and it will work perfectly.

I think I'm not understanding something here...

**Comment by zm711** [comment]
Definitely my poor explanation of the edge case I was thinking of. Sorry. 

I was imagining someone who already tried some curation in Phy, then decided to curate with SI and then tried to go back to Phy to visualize how their merges went and did something like 1+2 in Phy equals 10 and then in SI they want to merge 3 into 10 but decide to shrink the number back down to 1, 2, or 3. But maybe that is such an impossible case it doesn’t matter. (I haven’t tested this so really don’t know if it would even matter or whether SI internally fixes the issues).

**Review by alejoe91 — APPROVED** [review]

**Comment by DradeAW** [comment]
Thanks!

**Pull request merged**
