### PR TITLE
Add option `relative_to=True`

### PR DESCRIPTION
**Pull request by DradeAW**
Add the option to set `relative_to` to `True`, in which case it will be relative to the folder it's in.
As discussed with @alejoe91

### CODE REVIEW

**Comment by DradeAW** [comment]
Do you think `relative_to=True` should be the default behaviour?

Absolute paths are a pain because if you change computer or even the folder it's in, everything breaks :'(

**Comment by samuelgarcia** [comment]
Salut Aurelien,
I like this idea, we should have done before!
The only stuff I do not like so much which a typical python sweetmeat is that the same variable can be None or str or Path or bool!
To avoid this we need another variable this would be more explicit but more heavy let us think about it.

**Comment by DradeAW** [comment]
> the same variable can be None or str or Path or bool!

Now with the possibility of `True`, we can change `None -> False` I think.
But you're right, we are still left with `str | Path | bool`. I don't personally mind it, but I understand that it's not completely optimal. Although having 2 arguments also has its downsides ...

**Comment by alejoe91** [comment]
I would go with both options in the same argument!

**Comment by h-mayorquin** [comment]
I agree with @samuelgarcia about the typing. 

I think that the docstring could be changed from the current
```            If True, file_path is serialized relative to the folder of file_path ```

To something like "file and folder paths in extractor objects kwarsg are changed to be relative to this path or the parent folder"

Finally, It would be really nice if we started adding testing to the core funtionality. At least for the core.

**Review by alejoe91 — APPROVED** [review]

**Comment by DradeAW** [comment]
Do you want the default to be absolute paths (i.e. `relative_to=None`) or relative (i.e. `relative_to=True`)?

**Comment by alejoe91** [comment]
Absolute

**Comment by h-mayorquin** [comment]
The tests that were added just probe that no exception is raised. What I think we should test is if the different types work as intended. That is, if you pass a boolean and check that all the paths are written correctly.  This wil also serve the function of showing how the interface looks like.

**Review by samuelgarcia — APPROVED** [review]

**Pull request merged**
