### PR TITLE
`np.in1d` to `np.isin` as the former will be deprecated 

### PR DESCRIPTION
**Pull request by h-mayorquin**
Should address #1998.

### CODE REVIEW

**Comment by zm711** [comment]
@h-mayorquin 

it deleted the `np` for all of them.

**Comment by h-mayorquin** [comment]
Yeah, shame on my regex skills. Will fix right now.

**Comment by zm711** [comment]
> Yeah, shame on my regex skills. Will fix right now.

I can assure you better than mine. :)

**Review by yger — APPROVED** [review]
Looks good to me

**Review by samuelgarcia — APPROVED** [review]

**Comment by samuelgarcia** [comment]
Thanks you camarade.

**Pull request merged**
