### PR TITLE
Adding a savgol denoiser for the waveforms

### PR DESCRIPTION
**Pull request by yger**
I just made a simple (but efficient) savgol denoiser to smooth waveforms on-the-fly. I also fixed some typos in neuralnet denoiser

https://en.wikipedia.org/wiki/Savitzky%E2%80%93Golay_filter

### CODE REVIEW

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
Thanks @yger 

Looks good to me! @samuelgarcia @h-mayorquin wanna have a look?

**Comment by samuelgarcia** [comment]
OK for me also

**Comment by h-mayorquin** [comment]
Looks good to me. Great that you could use the fixtures over there. As both @alejoe91 and @samuelgarcia approved this I am merging it now.

I am thinking that this does not need the recording extractor as an argument (as the relevant frequency is extracted from the parent waveform extractor). I think this argument also applies to the temporal PCA and the NN denoiser. I will remove them in a future refactor.

**Comment by samuelgarcia** [comment]
Hi Ramon.
I am rather than for keeping the recording as an argument even if it is not need for some node.
Lets discuss this before a PR.

**Comment by h-mayorquin** [comment]
Ah, I see, yeah, let's discuss it!

**Pull request merged**
