### PR TITLE
Fix for nested tutorials

### PR DESCRIPTION
**Pull request by zm711**
This is a PR testing what is causing #1964. Since I can't recreate locally I will just test some things in the CI.

### CODE REVIEW

**Comment by zm711** [comment]
But if anyone else wants to try a test feel free to commit directly into this.

**Comment by zm711** [comment]
So moving core to the bottom of the ExplicitOrder switched it to be the nested tutorial. So there is something about the last entry in that order that is messing this up.

**Comment by zm711** [comment]
Still nested if I clean up the extra slashes.

**Comment by zm711** [comment]
So I started reading the `sphinx_gallery` issue tracker and seems like the fix is what I implemented. And looks fixed to me in the rtd build.

image
image

**Comment by zm711** [comment]
Fixes #1964

**Review by alejoe91 — APPROVED** [review]

**Comment by alejoe91** [comment]
Thank you si much Zach!

**Pull request merged**
